package com.bizvane.messageservice.mappers;

import com.bizvane.messagefacade.models.po.MsgMenuPlaceHolderRelPO;
import com.bizvane.messagefacade.models.po.MsgMenuPlaceHolderRelPOExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MsgMenuPlaceHolderRelPOMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_menu_placeholder_rel
	 * @mbg.generated  Fri Aug 31 14:01:37 CST 2018
	 */
	long countByExample(MsgMenuPlaceHolderRelPOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_menu_placeholder_rel
	 * @mbg.generated  Fri Aug 31 14:01:37 CST 2018
	 */
	int deleteByExample(MsgMenuPlaceHolderRelPOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_menu_placeholder_rel
	 * @mbg.generated  Fri Aug 31 14:01:37 CST 2018
	 */
	int deleteByPrimaryKey(Long msgMenuPlaceholderRelId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_menu_placeholder_rel
	 * @mbg.generated  Fri Aug 31 14:01:37 CST 2018
	 */
	int insert(MsgMenuPlaceHolderRelPO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_menu_placeholder_rel
	 * @mbg.generated  Fri Aug 31 14:01:37 CST 2018
	 */
	int insertSelective(MsgMenuPlaceHolderRelPO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_menu_placeholder_rel
	 * @mbg.generated  Fri Aug 31 14:01:37 CST 2018
	 */
	List<MsgMenuPlaceHolderRelPO> selectByExample(MsgMenuPlaceHolderRelPOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_menu_placeholder_rel
	 * @mbg.generated  Fri Aug 31 14:01:37 CST 2018
	 */
	MsgMenuPlaceHolderRelPO selectByPrimaryKey(Long msgMenuPlaceholderRelId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_menu_placeholder_rel
	 * @mbg.generated  Fri Aug 31 14:01:37 CST 2018
	 */
	int updateByExampleSelective(@Param("record") MsgMenuPlaceHolderRelPO record,
                                 @Param("example") MsgMenuPlaceHolderRelPOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_menu_placeholder_rel
	 * @mbg.generated  Fri Aug 31 14:01:37 CST 2018
	 */
	int updateByExample(@Param("record") MsgMenuPlaceHolderRelPO record,
                        @Param("example") MsgMenuPlaceHolderRelPOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_menu_placeholder_rel
	 * @mbg.generated  Fri Aug 31 14:01:37 CST 2018
	 */
	int updateByPrimaryKeySelective(MsgMenuPlaceHolderRelPO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_menu_placeholder_rel
	 * @mbg.generated  Fri Aug 31 14:01:37 CST 2018
	 */
	int updateByPrimaryKey(MsgMenuPlaceHolderRelPO record);

	List<MsgMenuPlaceHolderRelPO> findBytemplateType(String templateType);
}