package com.bizvane.messageservice.mappers;

import com.bizvane.messagefacade.models.po.MsgSmsPhonePO;
import com.bizvane.messagefacade.models.po.MsgSmsPhonePOExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MsgSmsPhonePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg_sms_phone
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    long countByExample(MsgSmsPhonePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg_sms_phone
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    int deleteByExample(MsgSmsPhonePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg_sms_phone
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    int deleteByPrimaryKey(Long msgSmsPhoneId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg_sms_phone
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    int insert(MsgSmsPhonePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg_sms_phone
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    int insertSelective(MsgSmsPhonePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg_sms_phone
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    List<MsgSmsPhonePO> selectByExample(MsgSmsPhonePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg_sms_phone
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    MsgSmsPhonePO selectByPrimaryKey(Long msgSmsPhoneId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg_sms_phone
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    int updateByExampleSelective(@Param("record") MsgSmsPhonePO record, @Param("example") MsgSmsPhonePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg_sms_phone
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    int updateByExample(@Param("record") MsgSmsPhonePO record, @Param("example") MsgSmsPhonePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg_sms_phone
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    int updateByPrimaryKeySelective(MsgSmsPhonePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg_sms_phone
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    int updateByPrimaryKey(MsgSmsPhonePO record);
}