package com.bizvane.messageservice.mappers;

import com.bizvane.messagefacade.models.po.MsgSmsLogPO;
import com.bizvane.messagefacade.models.po.MsgSmsLogPOExample;
import com.bizvane.messagefacade.models.vo.SmsMessageLogVo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MsgSmsLogPOMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_sms_log
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	long countByExample(MsgSmsLogPOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_sms_log
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	int deleteByExample(MsgSmsLogPOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_sms_log
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	int deleteByPrimaryKey(Long msgSmsLogId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_sms_log
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	int insert(MsgSmsLogPO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_sms_log
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	int insertSelective(MsgSmsLogPO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_sms_log
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	List<MsgSmsLogPO> selectByExampleWithBLOBs(MsgSmsLogPOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_sms_log
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	List<MsgSmsLogPO> selectByExample(MsgSmsLogPOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_sms_log
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	MsgSmsLogPO selectByPrimaryKey(Long msgSmsLogId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_sms_log
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	int updateByExampleSelective(@Param("record") MsgSmsLogPO record, @Param("example") MsgSmsLogPOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_sms_log
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	int updateByExampleWithBLOBs(@Param("record") MsgSmsLogPO record, @Param("example") MsgSmsLogPOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_sms_log
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	int updateByExample(@Param("record") MsgSmsLogPO record, @Param("example") MsgSmsLogPOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_sms_log
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	int updateByPrimaryKeySelective(MsgSmsLogPO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_sms_log
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	int updateByPrimaryKeyWithBLOBs(MsgSmsLogPO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_sms_log
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	int updateByPrimaryKey(MsgSmsLogPO record);

	List<MsgSmsLogPO> getMsgLogPage(SmsMessageLogVo smsMessageLogVo);

	Long getSuccessSms(SmsMessageLogVo smsMessageLogVo);

	Long getAllSms(SmsMessageLogVo smsMessageLogVo);
}