package com.bizvane.messageservice.mappers;

import com.bizvane.messagefacade.models.po.MsgWxLogPO;
import com.bizvane.messagefacade.models.po.MsgWxLogPOExample;
import com.bizvane.messagefacade.models.vo.WechatMessageLogVO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MsgWxLogPOMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_wx_log
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	long countByExample(MsgWxLogPOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_wx_log
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	int deleteByExample(MsgWxLogPOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_wx_log
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	int deleteByPrimaryKey(Long wechatMessageLogId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_wx_log
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	int insert(MsgWxLogPO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_wx_log
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	int insertSelective(MsgWxLogPO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_wx_log
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	List<MsgWxLogPO> selectByExample(MsgWxLogPOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_wx_log
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	MsgWxLogPO selectByPrimaryKey(Long wechatMessageLogId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_wx_log
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	int updateByExampleSelective(@Param("record") MsgWxLogPO record, @Param("example") MsgWxLogPOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_wx_log
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	int updateByExample(@Param("record") MsgWxLogPO record, @Param("example") MsgWxLogPOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_wx_log
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	int updateByPrimaryKeySelective(MsgWxLogPO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_wx_log
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	int updateByPrimaryKey(MsgWxLogPO record);

	/**
     * 查找微信消息日志分页
     * @param vo
     * @return
     */
    List<MsgWxLogPO> findPage(@Param("vo") WechatMessageLogVO vo);
    
    
    
}