package com.bizvane.messageservice.mappers;

import com.bizvane.messagefacade.models.po.SysSmsConfigPO;
import com.bizvane.messagefacade.models.po.SysSmsConfigPOExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysSmsConfigPOMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_sms_config
	 * @mbg.generated  Mon Aug 20 20:07:00 CST 2018
	 */
	long countByExample(SysSmsConfigPOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_sms_config
	 * @mbg.generated  Mon Aug 20 20:07:00 CST 2018
	 */
	int deleteByExample(SysSmsConfigPOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_sms_config
	 * @mbg.generated  Mon Aug 20 20:07:00 CST 2018
	 */
	int deleteByPrimaryKey(Long sysSmsConfigId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_sms_config
	 * @mbg.generated  Mon Aug 20 20:07:00 CST 2018
	 */
	int insert(SysSmsConfigPO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_sms_config
	 * @mbg.generated  Mon Aug 20 20:07:00 CST 2018
	 */
	int insertSelective(SysSmsConfigPO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_sms_config
	 * @mbg.generated  Mon Aug 20 20:07:00 CST 2018
	 */
	List<SysSmsConfigPO> selectByExample(SysSmsConfigPOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_sms_config
	 * @mbg.generated  Mon Aug 20 20:07:00 CST 2018
	 */
	SysSmsConfigPO selectByPrimaryKey(Long sysSmsConfigId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_sms_config
	 * @mbg.generated  Mon Aug 20 20:07:00 CST 2018
	 */
	int updateByExampleSelective(@Param("record") SysSmsConfigPO record,
                                 @Param("example") SysSmsConfigPOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_sms_config
	 * @mbg.generated  Mon Aug 20 20:07:00 CST 2018
	 */
	int updateByExample(@Param("record") SysSmsConfigPO record, @Param("example") SysSmsConfigPOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_sms_config
	 * @mbg.generated  Mon Aug 20 20:07:00 CST 2018
	 */
	int updateByPrimaryKeySelective(SysSmsConfigPO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_sms_config
	 * @mbg.generated  Mon Aug 20 20:07:00 CST 2018
	 */
	int updateByPrimaryKey(SysSmsConfigPO record);
}