package com.bizvane.messagefacade.models.po;

import java.util.Date;

public class DefSmsPlatformPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_def_sms_platform.platform_id
     *
     * @mbg.generated Mon Aug 20 20:07:00 CST 2018
     */
    private Long platformId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_def_sms_platform.platform_code
     *
     * @mbg.generated Mon Aug 20 20:07:00 CST 2018
     */
    private String platformCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_def_sms_platform.platform_name
     *
     * @mbg.generated Mon Aug 20 20:07:00 CST 2018
     */
    private String platformName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_def_sms_platform.remark
     *
     * @mbg.generated Mon Aug 20 20:07:00 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_def_sms_platform.create_user_id
     *
     * @mbg.generated Mon Aug 20 20:07:00 CST 2018
     */
    private Long createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_def_sms_platform.create_user_name
     *
     * @mbg.generated Mon Aug 20 20:07:00 CST 2018
     */
    private String createUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_def_sms_platform.create_date
     *
     * @mbg.generated Mon Aug 20 20:07:00 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_def_sms_platform.modified_user_id
     *
     * @mbg.generated Mon Aug 20 20:07:00 CST 2018
     */
    private Long modifiedUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_def_sms_platform.modified_user_name
     *
     * @mbg.generated Mon Aug 20 20:07:00 CST 2018
     */
    private String modifiedUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_def_sms_platform.modified_date
     *
     * @mbg.generated Mon Aug 20 20:07:00 CST 2018
     */
    private Date modifiedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_def_sms_platform.valid
     *
     * @mbg.generated Mon Aug 20 20:07:00 CST 2018
     */
    private Boolean valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_def_sms_platform.platform_id
     *
     * @return the value of t_def_sms_platform.platform_id
     *
     * @mbg.generated Mon Aug 20 20:07:00 CST 2018
     */
    public Long getPlatformId() {
        return platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_def_sms_platform.platform_id
     *
     * @param platformId the value for t_def_sms_platform.platform_id
     *
     * @mbg.generated Mon Aug 20 20:07:00 CST 2018
     */
    public void setPlatformId(Long platformId) {
        this.platformId = platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_def_sms_platform.platform_code
     *
     * @return the value of t_def_sms_platform.platform_code
     *
     * @mbg.generated Mon Aug 20 20:07:00 CST 2018
     */
    public String getPlatformCode() {
        return platformCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_def_sms_platform.platform_code
     *
     * @param platformCode the value for t_def_sms_platform.platform_code
     *
     * @mbg.generated Mon Aug 20 20:07:00 CST 2018
     */
    public void setPlatformCode(String platformCode) {
        this.platformCode = platformCode == null ? null : platformCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_def_sms_platform.platform_name
     *
     * @return the value of t_def_sms_platform.platform_name
     *
     * @mbg.generated Mon Aug 20 20:07:00 CST 2018
     */
    public String getPlatformName() {
        return platformName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_def_sms_platform.platform_name
     *
     * @param platformName the value for t_def_sms_platform.platform_name
     *
     * @mbg.generated Mon Aug 20 20:07:00 CST 2018
     */
    public void setPlatformName(String platformName) {
        this.platformName = platformName == null ? null : platformName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_def_sms_platform.remark
     *
     * @return the value of t_def_sms_platform.remark
     *
     * @mbg.generated Mon Aug 20 20:07:00 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_def_sms_platform.remark
     *
     * @param remark the value for t_def_sms_platform.remark
     *
     * @mbg.generated Mon Aug 20 20:07:00 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_def_sms_platform.create_user_id
     *
     * @return the value of t_def_sms_platform.create_user_id
     *
     * @mbg.generated Mon Aug 20 20:07:00 CST 2018
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_def_sms_platform.create_user_id
     *
     * @param createUserId the value for t_def_sms_platform.create_user_id
     *
     * @mbg.generated Mon Aug 20 20:07:00 CST 2018
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_def_sms_platform.create_user_name
     *
     * @return the value of t_def_sms_platform.create_user_name
     *
     * @mbg.generated Mon Aug 20 20:07:00 CST 2018
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_def_sms_platform.create_user_name
     *
     * @param createUserName the value for t_def_sms_platform.create_user_name
     *
     * @mbg.generated Mon Aug 20 20:07:00 CST 2018
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName == null ? null : createUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_def_sms_platform.create_date
     *
     * @return the value of t_def_sms_platform.create_date
     *
     * @mbg.generated Mon Aug 20 20:07:00 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_def_sms_platform.create_date
     *
     * @param createDate the value for t_def_sms_platform.create_date
     *
     * @mbg.generated Mon Aug 20 20:07:00 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_def_sms_platform.modified_user_id
     *
     * @return the value of t_def_sms_platform.modified_user_id
     *
     * @mbg.generated Mon Aug 20 20:07:00 CST 2018
     */
    public Long getModifiedUserId() {
        return modifiedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_def_sms_platform.modified_user_id
     *
     * @param modifiedUserId the value for t_def_sms_platform.modified_user_id
     *
     * @mbg.generated Mon Aug 20 20:07:00 CST 2018
     */
    public void setModifiedUserId(Long modifiedUserId) {
        this.modifiedUserId = modifiedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_def_sms_platform.modified_user_name
     *
     * @return the value of t_def_sms_platform.modified_user_name
     *
     * @mbg.generated Mon Aug 20 20:07:00 CST 2018
     */
    public String getModifiedUserName() {
        return modifiedUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_def_sms_platform.modified_user_name
     *
     * @param modifiedUserName the value for t_def_sms_platform.modified_user_name
     *
     * @mbg.generated Mon Aug 20 20:07:00 CST 2018
     */
    public void setModifiedUserName(String modifiedUserName) {
        this.modifiedUserName = modifiedUserName == null ? null : modifiedUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_def_sms_platform.modified_date
     *
     * @return the value of t_def_sms_platform.modified_date
     *
     * @mbg.generated Mon Aug 20 20:07:00 CST 2018
     */
    public Date getModifiedDate() {
        return modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_def_sms_platform.modified_date
     *
     * @param modifiedDate the value for t_def_sms_platform.modified_date
     *
     * @mbg.generated Mon Aug 20 20:07:00 CST 2018
     */
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_def_sms_platform.valid
     *
     * @return the value of t_def_sms_platform.valid
     *
     * @mbg.generated Mon Aug 20 20:07:00 CST 2018
     */
    public Boolean getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_def_sms_platform.valid
     *
     * @param valid the value for t_def_sms_platform.valid
     *
     * @mbg.generated Mon Aug 20 20:07:00 CST 2018
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }
}