package com.bizvane.messagefacade.models.po;

import java.util.Date;

public class MsgCoupontimePO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg_coupontime.msg_sendtime_id
     *
     * @mbg.generated Tue Sep 04 19:52:44 CST 2018
     */
    private Long msgSendtimeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg_coupontime.sys_company_id
     *
     * @mbg.generated Tue Sep 04 19:52:44 CST 2018
     */
    private Long sysCompanyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg_coupontime.sys_brand_id
     *
     * @mbg.generated Tue Sep 04 19:52:44 CST 2018
     */
    private Long sysBrandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg_coupontime.days
     *
     * @mbg.generated Tue Sep 04 19:52:44 CST 2018
     */
    private Long days;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg_coupontime.modified_user_id
     *
     * @mbg.generated Tue Sep 04 19:52:44 CST 2018
     */
    private Long modifiedUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg_coupontime.modified_user_name
     *
     * @mbg.generated Tue Sep 04 19:52:44 CST 2018
     */
    private String modifiedUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg_coupontime.modified_date
     *
     * @mbg.generated Tue Sep 04 19:52:44 CST 2018
     */
    private Date modifiedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg_coupontime.create_user_id
     *
     * @mbg.generated Tue Sep 04 19:52:44 CST 2018
     */
    private Long createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg_coupontime.create_user_name
     *
     * @mbg.generated Tue Sep 04 19:52:44 CST 2018
     */
    private String createUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg_coupontime.create_date
     *
     * @mbg.generated Tue Sep 04 19:52:44 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg_coupontime.valid
     *
     * @mbg.generated Tue Sep 04 19:52:44 CST 2018
     */
    private Boolean valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_coupontime.msg_sendtime_id
     *
     * @return the value of t_msg_coupontime.msg_sendtime_id
     *
     * @mbg.generated Tue Sep 04 19:52:44 CST 2018
     */
    public Long getMsgSendtimeId() {
        return msgSendtimeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_coupontime.msg_sendtime_id
     *
     * @param msgSendtimeId the value for t_msg_coupontime.msg_sendtime_id
     *
     * @mbg.generated Tue Sep 04 19:52:44 CST 2018
     */
    public void setMsgSendtimeId(Long msgSendtimeId) {
        this.msgSendtimeId = msgSendtimeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_coupontime.sys_company_id
     *
     * @return the value of t_msg_coupontime.sys_company_id
     *
     * @mbg.generated Tue Sep 04 19:52:44 CST 2018
     */
    public Long getSysCompanyId() {
        return sysCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_coupontime.sys_company_id
     *
     * @param sysCompanyId the value for t_msg_coupontime.sys_company_id
     *
     * @mbg.generated Tue Sep 04 19:52:44 CST 2018
     */
    public void setSysCompanyId(Long sysCompanyId) {
        this.sysCompanyId = sysCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_coupontime.sys_brand_id
     *
     * @return the value of t_msg_coupontime.sys_brand_id
     *
     * @mbg.generated Tue Sep 04 19:52:44 CST 2018
     */
    public Long getSysBrandId() {
        return sysBrandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_coupontime.sys_brand_id
     *
     * @param sysBrandId the value for t_msg_coupontime.sys_brand_id
     *
     * @mbg.generated Tue Sep 04 19:52:44 CST 2018
     */
    public void setSysBrandId(Long sysBrandId) {
        this.sysBrandId = sysBrandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_coupontime.days
     *
     * @return the value of t_msg_coupontime.days
     *
     * @mbg.generated Tue Sep 04 19:52:44 CST 2018
     */
    public Long getDays() {
        return days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_coupontime.days
     *
     * @param days the value for t_msg_coupontime.days
     *
     * @mbg.generated Tue Sep 04 19:52:44 CST 2018
     */
    public void setDays(Long days) {
        this.days = days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_coupontime.modified_user_id
     *
     * @return the value of t_msg_coupontime.modified_user_id
     *
     * @mbg.generated Tue Sep 04 19:52:44 CST 2018
     */
    public Long getModifiedUserId() {
        return modifiedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_coupontime.modified_user_id
     *
     * @param modifiedUserId the value for t_msg_coupontime.modified_user_id
     *
     * @mbg.generated Tue Sep 04 19:52:44 CST 2018
     */
    public void setModifiedUserId(Long modifiedUserId) {
        this.modifiedUserId = modifiedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_coupontime.modified_user_name
     *
     * @return the value of t_msg_coupontime.modified_user_name
     *
     * @mbg.generated Tue Sep 04 19:52:44 CST 2018
     */
    public String getModifiedUserName() {
        return modifiedUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_coupontime.modified_user_name
     *
     * @param modifiedUserName the value for t_msg_coupontime.modified_user_name
     *
     * @mbg.generated Tue Sep 04 19:52:44 CST 2018
     */
    public void setModifiedUserName(String modifiedUserName) {
        this.modifiedUserName = modifiedUserName == null ? null : modifiedUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_coupontime.modified_date
     *
     * @return the value of t_msg_coupontime.modified_date
     *
     * @mbg.generated Tue Sep 04 19:52:44 CST 2018
     */
    public Date getModifiedDate() {
        return modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_coupontime.modified_date
     *
     * @param modifiedDate the value for t_msg_coupontime.modified_date
     *
     * @mbg.generated Tue Sep 04 19:52:44 CST 2018
     */
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_coupontime.create_user_id
     *
     * @return the value of t_msg_coupontime.create_user_id
     *
     * @mbg.generated Tue Sep 04 19:52:44 CST 2018
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_coupontime.create_user_id
     *
     * @param createUserId the value for t_msg_coupontime.create_user_id
     *
     * @mbg.generated Tue Sep 04 19:52:44 CST 2018
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_coupontime.create_user_name
     *
     * @return the value of t_msg_coupontime.create_user_name
     *
     * @mbg.generated Tue Sep 04 19:52:44 CST 2018
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_coupontime.create_user_name
     *
     * @param createUserName the value for t_msg_coupontime.create_user_name
     *
     * @mbg.generated Tue Sep 04 19:52:44 CST 2018
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName == null ? null : createUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_coupontime.create_date
     *
     * @return the value of t_msg_coupontime.create_date
     *
     * @mbg.generated Tue Sep 04 19:52:44 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_coupontime.create_date
     *
     * @param createDate the value for t_msg_coupontime.create_date
     *
     * @mbg.generated Tue Sep 04 19:52:44 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_coupontime.valid
     *
     * @return the value of t_msg_coupontime.valid
     *
     * @mbg.generated Tue Sep 04 19:52:44 CST 2018
     */
    public Boolean getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_coupontime.valid
     *
     * @param valid the value for t_msg_coupontime.valid
     *
     * @mbg.generated Tue Sep 04 19:52:44 CST 2018
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }
}