package com.bizvane.messagefacade.models.po;

import java.util.Date;

public class MsgSmsPhonePO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg_sms_phone.msg_sms_phone_id
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    private Long msgSmsPhoneId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg_sms_phone.sys_company_id
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    private Long sysCompanyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg_sms_phone.sys_brand_id
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    private Long sysBrandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg_sms_phone.phone
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg_sms_phone.template_type
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    private Boolean templateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg_sms_phone.status
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg_sms_phone.remark
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg_sms_phone.tem
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    private String tem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg_sms_phone.create_user_id
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    private Long createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg_sms_phone.create_user_name
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    private String createUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg_sms_phone.create_date
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg_sms_phone.modified_user_id
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    private Long modifiedUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg_sms_phone.modified_user_name
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    private String modifiedUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg_sms_phone.modified_date
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    private Date modifiedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg_sms_phone.valid
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    private Boolean valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_sms_phone.msg_sms_phone_id
     *
     * @return the value of t_msg_sms_phone.msg_sms_phone_id
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    public Long getMsgSmsPhoneId() {
        return msgSmsPhoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_sms_phone.msg_sms_phone_id
     *
     * @param msgSmsPhoneId the value for t_msg_sms_phone.msg_sms_phone_id
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    public void setMsgSmsPhoneId(Long msgSmsPhoneId) {
        this.msgSmsPhoneId = msgSmsPhoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_sms_phone.sys_company_id
     *
     * @return the value of t_msg_sms_phone.sys_company_id
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    public Long getSysCompanyId() {
        return sysCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_sms_phone.sys_company_id
     *
     * @param sysCompanyId the value for t_msg_sms_phone.sys_company_id
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    public void setSysCompanyId(Long sysCompanyId) {
        this.sysCompanyId = sysCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_sms_phone.sys_brand_id
     *
     * @return the value of t_msg_sms_phone.sys_brand_id
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    public Long getSysBrandId() {
        return sysBrandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_sms_phone.sys_brand_id
     *
     * @param sysBrandId the value for t_msg_sms_phone.sys_brand_id
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    public void setSysBrandId(Long sysBrandId) {
        this.sysBrandId = sysBrandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_sms_phone.phone
     *
     * @return the value of t_msg_sms_phone.phone
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_sms_phone.phone
     *
     * @param phone the value for t_msg_sms_phone.phone
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_sms_phone.template_type
     *
     * @return the value of t_msg_sms_phone.template_type
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    public Boolean getTemplateType() {
        return templateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_sms_phone.template_type
     *
     * @param templateType the value for t_msg_sms_phone.template_type
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    public void setTemplateType(Boolean templateType) {
        this.templateType = templateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_sms_phone.status
     *
     * @return the value of t_msg_sms_phone.status
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_sms_phone.status
     *
     * @param status the value for t_msg_sms_phone.status
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_sms_phone.remark
     *
     * @return the value of t_msg_sms_phone.remark
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_sms_phone.remark
     *
     * @param remark the value for t_msg_sms_phone.remark
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_sms_phone.tem
     *
     * @return the value of t_msg_sms_phone.tem
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    public String getTem() {
        return tem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_sms_phone.tem
     *
     * @param tem the value for t_msg_sms_phone.tem
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    public void setTem(String tem) {
        this.tem = tem == null ? null : tem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_sms_phone.create_user_id
     *
     * @return the value of t_msg_sms_phone.create_user_id
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_sms_phone.create_user_id
     *
     * @param createUserId the value for t_msg_sms_phone.create_user_id
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_sms_phone.create_user_name
     *
     * @return the value of t_msg_sms_phone.create_user_name
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_sms_phone.create_user_name
     *
     * @param createUserName the value for t_msg_sms_phone.create_user_name
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName == null ? null : createUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_sms_phone.create_date
     *
     * @return the value of t_msg_sms_phone.create_date
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_sms_phone.create_date
     *
     * @param createDate the value for t_msg_sms_phone.create_date
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_sms_phone.modified_user_id
     *
     * @return the value of t_msg_sms_phone.modified_user_id
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    public Long getModifiedUserId() {
        return modifiedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_sms_phone.modified_user_id
     *
     * @param modifiedUserId the value for t_msg_sms_phone.modified_user_id
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    public void setModifiedUserId(Long modifiedUserId) {
        this.modifiedUserId = modifiedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_sms_phone.modified_user_name
     *
     * @return the value of t_msg_sms_phone.modified_user_name
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    public String getModifiedUserName() {
        return modifiedUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_sms_phone.modified_user_name
     *
     * @param modifiedUserName the value for t_msg_sms_phone.modified_user_name
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    public void setModifiedUserName(String modifiedUserName) {
        this.modifiedUserName = modifiedUserName == null ? null : modifiedUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_sms_phone.modified_date
     *
     * @return the value of t_msg_sms_phone.modified_date
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    public Date getModifiedDate() {
        return modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_sms_phone.modified_date
     *
     * @param modifiedDate the value for t_msg_sms_phone.modified_date
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_sms_phone.valid
     *
     * @return the value of t_msg_sms_phone.valid
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    public Boolean getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_sms_phone.valid
     *
     * @param valid the value for t_msg_sms_phone.valid
     *
     * @mbg.generated Fri Oct 26 14:54:10 CST 2018
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }
}