package com.bizvane.messagefacade.models.po;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MsgSmsLogPOExample implements Serializable {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_msg_sms_log
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_msg_sms_log
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_msg_sms_log
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_sms_log
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	public MsgSmsLogPOExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_sms_log
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_sms_log
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_sms_log
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_sms_log
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_sms_log
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_sms_log
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_sms_log
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_sms_log
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_sms_log
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_msg_sms_log
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_msg_sms_log
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andMsgSmsLogIdIsNull() {
			addCriterion("msg_sms_log_id is null");
			return (Criteria) this;
		}

		public Criteria andMsgSmsLogIdIsNotNull() {
			addCriterion("msg_sms_log_id is not null");
			return (Criteria) this;
		}

		public Criteria andMsgSmsLogIdEqualTo(Long value) {
			addCriterion("msg_sms_log_id =", value, "msgSmsLogId");
			return (Criteria) this;
		}

		public Criteria andMsgSmsLogIdNotEqualTo(Long value) {
			addCriterion("msg_sms_log_id <>", value, "msgSmsLogId");
			return (Criteria) this;
		}

		public Criteria andMsgSmsLogIdGreaterThan(Long value) {
			addCriterion("msg_sms_log_id >", value, "msgSmsLogId");
			return (Criteria) this;
		}

		public Criteria andMsgSmsLogIdGreaterThanOrEqualTo(Long value) {
			addCriterion("msg_sms_log_id >=", value, "msgSmsLogId");
			return (Criteria) this;
		}

		public Criteria andMsgSmsLogIdLessThan(Long value) {
			addCriterion("msg_sms_log_id <", value, "msgSmsLogId");
			return (Criteria) this;
		}

		public Criteria andMsgSmsLogIdLessThanOrEqualTo(Long value) {
			addCriterion("msg_sms_log_id <=", value, "msgSmsLogId");
			return (Criteria) this;
		}

		public Criteria andMsgSmsLogIdIn(List<Long> values) {
			addCriterion("msg_sms_log_id in", values, "msgSmsLogId");
			return (Criteria) this;
		}

		public Criteria andMsgSmsLogIdNotIn(List<Long> values) {
			addCriterion("msg_sms_log_id not in", values, "msgSmsLogId");
			return (Criteria) this;
		}

		public Criteria andMsgSmsLogIdBetween(Long value1, Long value2) {
			addCriterion("msg_sms_log_id between", value1, value2, "msgSmsLogId");
			return (Criteria) this;
		}

		public Criteria andMsgSmsLogIdNotBetween(Long value1, Long value2) {
			addCriterion("msg_sms_log_id not between", value1, value2, "msgSmsLogId");
			return (Criteria) this;
		}

		public Criteria andSysCompanyIdIsNull() {
			addCriterion("sys_company_id is null");
			return (Criteria) this;
		}

		public Criteria andSysCompanyIdIsNotNull() {
			addCriterion("sys_company_id is not null");
			return (Criteria) this;
		}

		public Criteria andSysCompanyIdEqualTo(Long value) {
			addCriterion("sys_company_id =", value, "sysCompanyId");
			return (Criteria) this;
		}

		public Criteria andSysCompanyIdNotEqualTo(Long value) {
			addCriterion("sys_company_id <>", value, "sysCompanyId");
			return (Criteria) this;
		}

		public Criteria andSysCompanyIdGreaterThan(Long value) {
			addCriterion("sys_company_id >", value, "sysCompanyId");
			return (Criteria) this;
		}

		public Criteria andSysCompanyIdGreaterThanOrEqualTo(Long value) {
			addCriterion("sys_company_id >=", value, "sysCompanyId");
			return (Criteria) this;
		}

		public Criteria andSysCompanyIdLessThan(Long value) {
			addCriterion("sys_company_id <", value, "sysCompanyId");
			return (Criteria) this;
		}

		public Criteria andSysCompanyIdLessThanOrEqualTo(Long value) {
			addCriterion("sys_company_id <=", value, "sysCompanyId");
			return (Criteria) this;
		}

		public Criteria andSysCompanyIdIn(List<Long> values) {
			addCriterion("sys_company_id in", values, "sysCompanyId");
			return (Criteria) this;
		}

		public Criteria andSysCompanyIdNotIn(List<Long> values) {
			addCriterion("sys_company_id not in", values, "sysCompanyId");
			return (Criteria) this;
		}

		public Criteria andSysCompanyIdBetween(Long value1, Long value2) {
			addCriterion("sys_company_id between", value1, value2, "sysCompanyId");
			return (Criteria) this;
		}

		public Criteria andSysCompanyIdNotBetween(Long value1, Long value2) {
			addCriterion("sys_company_id not between", value1, value2, "sysCompanyId");
			return (Criteria) this;
		}

		public Criteria andTemplateTypeIsNull() {
			addCriterion("template_type is null");
			return (Criteria) this;
		}

		public Criteria andTemplateTypeIsNotNull() {
			addCriterion("template_type is not null");
			return (Criteria) this;
		}

		public Criteria andTemplateTypeEqualTo(String value) {
			addCriterion("template_type =", value, "templateType");
			return (Criteria) this;
		}

		public Criteria andTemplateTypeNotEqualTo(String value) {
			addCriterion("template_type <>", value, "templateType");
			return (Criteria) this;
		}

		public Criteria andTemplateTypeGreaterThan(String value) {
			addCriterion("template_type >", value, "templateType");
			return (Criteria) this;
		}

		public Criteria andTemplateTypeGreaterThanOrEqualTo(String value) {
			addCriterion("template_type >=", value, "templateType");
			return (Criteria) this;
		}

		public Criteria andTemplateTypeLessThan(String value) {
			addCriterion("template_type <", value, "templateType");
			return (Criteria) this;
		}

		public Criteria andTemplateTypeLessThanOrEqualTo(String value) {
			addCriterion("template_type <=", value, "templateType");
			return (Criteria) this;
		}

		public Criteria andTemplateTypeLike(String value) {
			addCriterion("template_type like", value, "templateType");
			return (Criteria) this;
		}

		public Criteria andTemplateTypeNotLike(String value) {
			addCriterion("template_type not like", value, "templateType");
			return (Criteria) this;
		}

		public Criteria andTemplateTypeIn(List<String> values) {
			addCriterion("template_type in", values, "templateType");
			return (Criteria) this;
		}

		public Criteria andTemplateTypeNotIn(List<String> values) {
			addCriterion("template_type not in", values, "templateType");
			return (Criteria) this;
		}

		public Criteria andTemplateTypeBetween(String value1, String value2) {
			addCriterion("template_type between", value1, value2, "templateType");
			return (Criteria) this;
		}

		public Criteria andTemplateTypeNotBetween(String value1, String value2) {
			addCriterion("template_type not between", value1, value2, "templateType");
			return (Criteria) this;
		}

		public Criteria andBussinessIdIsNull() {
			addCriterion("bussiness_id is null");
			return (Criteria) this;
		}

		public Criteria andBussinessIdIsNotNull() {
			addCriterion("bussiness_id is not null");
			return (Criteria) this;
		}

		public Criteria andBussinessIdEqualTo(String value) {
			addCriterion("bussiness_id =", value, "bussinessId");
			return (Criteria) this;
		}

		public Criteria andBussinessIdNotEqualTo(String value) {
			addCriterion("bussiness_id <>", value, "bussinessId");
			return (Criteria) this;
		}

		public Criteria andBussinessIdGreaterThan(String value) {
			addCriterion("bussiness_id >", value, "bussinessId");
			return (Criteria) this;
		}

		public Criteria andBussinessIdGreaterThanOrEqualTo(String value) {
			addCriterion("bussiness_id >=", value, "bussinessId");
			return (Criteria) this;
		}

		public Criteria andBussinessIdLessThan(String value) {
			addCriterion("bussiness_id <", value, "bussinessId");
			return (Criteria) this;
		}

		public Criteria andBussinessIdLessThanOrEqualTo(String value) {
			addCriterion("bussiness_id <=", value, "bussinessId");
			return (Criteria) this;
		}

		public Criteria andBussinessIdLike(String value) {
			addCriterion("bussiness_id like", value, "bussinessId");
			return (Criteria) this;
		}

		public Criteria andBussinessIdNotLike(String value) {
			addCriterion("bussiness_id not like", value, "bussinessId");
			return (Criteria) this;
		}

		public Criteria andBussinessIdIn(List<String> values) {
			addCriterion("bussiness_id in", values, "bussinessId");
			return (Criteria) this;
		}

		public Criteria andBussinessIdNotIn(List<String> values) {
			addCriterion("bussiness_id not in", values, "bussinessId");
			return (Criteria) this;
		}

		public Criteria andBussinessIdBetween(String value1, String value2) {
			addCriterion("bussiness_id between", value1, value2, "bussinessId");
			return (Criteria) this;
		}

		public Criteria andBussinessIdNotBetween(String value1, String value2) {
			addCriterion("bussiness_id not between", value1, value2, "bussinessId");
			return (Criteria) this;
		}

		public Criteria andMemberNameIsNull() {
			addCriterion("member_name is null");
			return (Criteria) this;
		}

		public Criteria andMemberNameIsNotNull() {
			addCriterion("member_name is not null");
			return (Criteria) this;
		}

		public Criteria andMemberNameEqualTo(String value) {
			addCriterion("member_name =", value, "memberName");
			return (Criteria) this;
		}

		public Criteria andMemberNameNotEqualTo(String value) {
			addCriterion("member_name <>", value, "memberName");
			return (Criteria) this;
		}

		public Criteria andMemberNameGreaterThan(String value) {
			addCriterion("member_name >", value, "memberName");
			return (Criteria) this;
		}

		public Criteria andMemberNameGreaterThanOrEqualTo(String value) {
			addCriterion("member_name >=", value, "memberName");
			return (Criteria) this;
		}

		public Criteria andMemberNameLessThan(String value) {
			addCriterion("member_name <", value, "memberName");
			return (Criteria) this;
		}

		public Criteria andMemberNameLessThanOrEqualTo(String value) {
			addCriterion("member_name <=", value, "memberName");
			return (Criteria) this;
		}

		public Criteria andMemberNameLike(String value) {
			addCriterion("member_name like", value, "memberName");
			return (Criteria) this;
		}

		public Criteria andMemberNameNotLike(String value) {
			addCriterion("member_name not like", value, "memberName");
			return (Criteria) this;
		}

		public Criteria andMemberNameIn(List<String> values) {
			addCriterion("member_name in", values, "memberName");
			return (Criteria) this;
		}

		public Criteria andMemberNameNotIn(List<String> values) {
			addCriterion("member_name not in", values, "memberName");
			return (Criteria) this;
		}

		public Criteria andMemberNameBetween(String value1, String value2) {
			addCriterion("member_name between", value1, value2, "memberName");
			return (Criteria) this;
		}

		public Criteria andMemberNameNotBetween(String value1, String value2) {
			addCriterion("member_name not between", value1, value2, "memberName");
			return (Criteria) this;
		}

		public Criteria andMemberPhoneIsNull() {
			addCriterion("member_phone is null");
			return (Criteria) this;
		}

		public Criteria andMemberPhoneIsNotNull() {
			addCriterion("member_phone is not null");
			return (Criteria) this;
		}

		public Criteria andMemberPhoneEqualTo(String value) {
			addCriterion("member_phone =", value, "memberPhone");
			return (Criteria) this;
		}

		public Criteria andMemberPhoneNotEqualTo(String value) {
			addCriterion("member_phone <>", value, "memberPhone");
			return (Criteria) this;
		}

		public Criteria andMemberPhoneGreaterThan(String value) {
			addCriterion("member_phone >", value, "memberPhone");
			return (Criteria) this;
		}

		public Criteria andMemberPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("member_phone >=", value, "memberPhone");
			return (Criteria) this;
		}

		public Criteria andMemberPhoneLessThan(String value) {
			addCriterion("member_phone <", value, "memberPhone");
			return (Criteria) this;
		}

		public Criteria andMemberPhoneLessThanOrEqualTo(String value) {
			addCriterion("member_phone <=", value, "memberPhone");
			return (Criteria) this;
		}

		public Criteria andMemberPhoneLike(String value) {
			addCriterion("member_phone like", value, "memberPhone");
			return (Criteria) this;
		}

		public Criteria andMemberPhoneNotLike(String value) {
			addCriterion("member_phone not like", value, "memberPhone");
			return (Criteria) this;
		}

		public Criteria andMemberPhoneIn(List<String> values) {
			addCriterion("member_phone in", values, "memberPhone");
			return (Criteria) this;
		}

		public Criteria andMemberPhoneNotIn(List<String> values) {
			addCriterion("member_phone not in", values, "memberPhone");
			return (Criteria) this;
		}

		public Criteria andMemberPhoneBetween(String value1, String value2) {
			addCriterion("member_phone between", value1, value2, "memberPhone");
			return (Criteria) this;
		}

		public Criteria andMemberPhoneNotBetween(String value1, String value2) {
			addCriterion("member_phone not between", value1, value2, "memberPhone");
			return (Criteria) this;
		}

		public Criteria andResultInfoIsNull() {
			addCriterion("result_info is null");
			return (Criteria) this;
		}

		public Criteria andResultInfoIsNotNull() {
			addCriterion("result_info is not null");
			return (Criteria) this;
		}

		public Criteria andResultInfoEqualTo(String value) {
			addCriterion("result_info =", value, "resultInfo");
			return (Criteria) this;
		}

		public Criteria andResultInfoNotEqualTo(String value) {
			addCriterion("result_info <>", value, "resultInfo");
			return (Criteria) this;
		}

		public Criteria andResultInfoGreaterThan(String value) {
			addCriterion("result_info >", value, "resultInfo");
			return (Criteria) this;
		}

		public Criteria andResultInfoGreaterThanOrEqualTo(String value) {
			addCriterion("result_info >=", value, "resultInfo");
			return (Criteria) this;
		}

		public Criteria andResultInfoLessThan(String value) {
			addCriterion("result_info <", value, "resultInfo");
			return (Criteria) this;
		}

		public Criteria andResultInfoLessThanOrEqualTo(String value) {
			addCriterion("result_info <=", value, "resultInfo");
			return (Criteria) this;
		}

		public Criteria andResultInfoLike(String value) {
			addCriterion("result_info like", value, "resultInfo");
			return (Criteria) this;
		}

		public Criteria andResultInfoNotLike(String value) {
			addCriterion("result_info not like", value, "resultInfo");
			return (Criteria) this;
		}

		public Criteria andResultInfoIn(List<String> values) {
			addCriterion("result_info in", values, "resultInfo");
			return (Criteria) this;
		}

		public Criteria andResultInfoNotIn(List<String> values) {
			addCriterion("result_info not in", values, "resultInfo");
			return (Criteria) this;
		}

		public Criteria andResultInfoBetween(String value1, String value2) {
			addCriterion("result_info between", value1, value2, "resultInfo");
			return (Criteria) this;
		}

		public Criteria andResultInfoNotBetween(String value1, String value2) {
			addCriterion("result_info not between", value1, value2, "resultInfo");
			return (Criteria) this;
		}

		public Criteria andSendStateIsNull() {
			addCriterion("send_state is null");
			return (Criteria) this;
		}

		public Criteria andSendStateIsNotNull() {
			addCriterion("send_state is not null");
			return (Criteria) this;
		}

		public Criteria andSendStateEqualTo(Integer value) {
			addCriterion("send_state =", value, "sendState");
			return (Criteria) this;
		}

		public Criteria andSendStateNotEqualTo(Integer value) {
			addCriterion("send_state <>", value, "sendState");
			return (Criteria) this;
		}

		public Criteria andSendStateGreaterThan(Integer value) {
			addCriterion("send_state >", value, "sendState");
			return (Criteria) this;
		}

		public Criteria andSendStateGreaterThanOrEqualTo(Integer value) {
			addCriterion("send_state >=", value, "sendState");
			return (Criteria) this;
		}

		public Criteria andSendStateLessThan(Integer value) {
			addCriterion("send_state <", value, "sendState");
			return (Criteria) this;
		}

		public Criteria andSendStateLessThanOrEqualTo(Integer value) {
			addCriterion("send_state <=", value, "sendState");
			return (Criteria) this;
		}

		public Criteria andSendStateIn(List<Integer> values) {
			addCriterion("send_state in", values, "sendState");
			return (Criteria) this;
		}

		public Criteria andSendStateNotIn(List<Integer> values) {
			addCriterion("send_state not in", values, "sendState");
			return (Criteria) this;
		}

		public Criteria andSendStateBetween(Integer value1, Integer value2) {
			addCriterion("send_state between", value1, value2, "sendState");
			return (Criteria) this;
		}

		public Criteria andSendStateNotBetween(Integer value1, Integer value2) {
			addCriterion("send_state not between", value1, value2, "sendState");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdIsNull() {
			addCriterion("update_user_id is null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdIsNotNull() {
			addCriterion("update_user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdEqualTo(Integer value) {
			addCriterion("update_user_id =", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdNotEqualTo(Integer value) {
			addCriterion("update_user_id <>", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdGreaterThan(Integer value) {
			addCriterion("update_user_id >", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("update_user_id >=", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdLessThan(Integer value) {
			addCriterion("update_user_id <", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdLessThanOrEqualTo(Integer value) {
			addCriterion("update_user_id <=", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdIn(List<Integer> values) {
			addCriterion("update_user_id in", values, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdNotIn(List<Integer> values) {
			addCriterion("update_user_id not in", values, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdBetween(Integer value1, Integer value2) {
			addCriterion("update_user_id between", value1, value2, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdNotBetween(Integer value1, Integer value2) {
			addCriterion("update_user_id not between", value1, value2, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNull() {
			addCriterion("update_date is null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNotNull() {
			addCriterion("update_date is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateEqualTo(Date value) {
			addCriterion("update_date =", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotEqualTo(Date value) {
			addCriterion("update_date <>", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThan(Date value) {
			addCriterion("update_date >", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("update_date >=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThan(Date value) {
			addCriterion("update_date <", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
			addCriterion("update_date <=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIn(List<Date> values) {
			addCriterion("update_date in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotIn(List<Date> values) {
			addCriterion("update_date not in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateBetween(Date value1, Date value2) {
			addCriterion("update_date between", value1, value2, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
			addCriterion("update_date not between", value1, value2, "updateDate");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdIsNull() {
			addCriterion("create_user_id is null");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdIsNotNull() {
			addCriterion("create_user_id is not null");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdEqualTo(Integer value) {
			addCriterion("create_user_id =", value, "createUserId");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdNotEqualTo(Integer value) {
			addCriterion("create_user_id <>", value, "createUserId");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdGreaterThan(Integer value) {
			addCriterion("create_user_id >", value, "createUserId");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("create_user_id >=", value, "createUserId");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdLessThan(Integer value) {
			addCriterion("create_user_id <", value, "createUserId");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdLessThanOrEqualTo(Integer value) {
			addCriterion("create_user_id <=", value, "createUserId");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdIn(List<Integer> values) {
			addCriterion("create_user_id in", values, "createUserId");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdNotIn(List<Integer> values) {
			addCriterion("create_user_id not in", values, "createUserId");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdBetween(Integer value1, Integer value2) {
			addCriterion("create_user_id between", value1, value2, "createUserId");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdNotBetween(Integer value1, Integer value2) {
			addCriterion("create_user_id not between", value1, value2, "createUserId");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNull() {
			addCriterion("create_date is null");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNotNull() {
			addCriterion("create_date is not null");
			return (Criteria) this;
		}

		public Criteria andCreateDateEqualTo(Date value) {
			addCriterion("create_date =", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotEqualTo(Date value) {
			addCriterion("create_date <>", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThan(Date value) {
			addCriterion("create_date >", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("create_date >=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThan(Date value) {
			addCriterion("create_date <", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThanOrEqualTo(Date value) {
			addCriterion("create_date <=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateIn(List<Date> values) {
			addCriterion("create_date in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotIn(List<Date> values) {
			addCriterion("create_date not in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateBetween(Date value1, Date value2) {
			addCriterion("create_date between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotBetween(Date value1, Date value2) {
			addCriterion("create_date not between", value1, value2, "createDate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_msg_sms_log
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**9
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_msg_sms_log
     *
     * @mbg.generated do_not_delete_during_merge 2018-08-08 19:53:52
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }
}