package com.bizvane.messagefacade.models.po;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;

public class MsgSmsLogPO implements Serializable {


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_msg_sms_log.msg_sms_log_id
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	@io.swagger.annotations.ApiModelProperty(value = "主键id", name = "msgSmsLogId", required = false, example = "")
	private Long msgSmsLogId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_msg_sms_log.sys_company_id
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	private Long sysCompanyId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_msg_sms_log.template_type
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	@io.swagger.annotations.ApiModelProperty(value = "短信模板类型", name = "templateType", required = false, example = "")
	private String templateType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_msg_sms_log.bussiness_id
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	@io.swagger.annotations.ApiModelProperty(value = "业务单据号", name = "bussinessId", required = false, example = "")
	private String bussinessId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_msg_sms_log.member_name
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	@io.swagger.annotations.ApiModelProperty(value = "会员姓名", name = "memberName", required = false, example = "")
	private String memberName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_msg_sms_log.member_phone
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	@io.swagger.annotations.ApiModelProperty(value = "会员手机号码", name = "memberPhone", required = false, example = "")
	private String memberPhone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_msg_sms_log.result_info
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	@io.swagger.annotations.ApiModelProperty(value = "返回数据", name = "resultInfo", required = false, example = "")
	private String resultInfo;
	@io.swagger.annotations.ApiModelProperty(value = "返回数据明细信息", name = "resultInfoDetail", required = false, example = "")
	private String resultInfoDetail;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_msg_sms_log.send_state
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	@io.swagger.annotations.ApiModelProperty(value = "发送状态（发送结果）：0-全部；-1-失败；1-成功；", name = "sendState", required = false, example = "")
	private Integer sendState;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_msg_sms_log.update_user_id
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	@io.swagger.annotations.ApiModelProperty(value = "最后修改人", name = "updateUserId", required = false, example = "")
	private Integer updateUserId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_msg_sms_log.update_date
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
	@io.swagger.annotations.ApiModelProperty(value = "最后修改日期", name = "updateDate", required = false, example = "")
	private Date updateDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_msg_sms_log.create_user_id
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	@io.swagger.annotations.ApiModelProperty(value = "创建人", name = "createUserId", required = false, example = "")
	private Integer createUserId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_msg_sms_log.create_date
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
	@io.swagger.annotations.ApiModelProperty(value = "创建日期（发送时间）", name = "createDate", required = false, example = "")
	private Date createDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_msg_sms_log.message_body
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	@io.swagger.annotations.ApiModelProperty(value = "短信内容(消息内容)", name = "messageBody", required = false, example = "")
	private String messageBody;
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_msg_sms_log.msg_sms_log_id
	 * @return  the value of t_msg_sms_log.msg_sms_log_id
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	public Long getMsgSmsLogId() {
		return msgSmsLogId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_msg_sms_log.msg_sms_log_id
	 * @param msgSmsLogId  the value for t_msg_sms_log.msg_sms_log_id
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	public void setMsgSmsLogId(Long msgSmsLogId) {
		this.msgSmsLogId = msgSmsLogId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_msg_sms_log.sys_company_id
	 * @return  the value of t_msg_sms_log.sys_company_id
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	public Long getSysCompanyId() {
		return sysCompanyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_msg_sms_log.sys_company_id
	 * @param sysCompanyId  the value for t_msg_sms_log.sys_company_id
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	public void setSysCompanyId(Long sysCompanyId) {
		this.sysCompanyId = sysCompanyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_msg_sms_log.template_type
	 * @return  the value of t_msg_sms_log.template_type
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	public String getTemplateType() {
		return templateType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_msg_sms_log.template_type
	 * @param templateType  the value for t_msg_sms_log.template_type
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	public void setTemplateType(String templateType) {
		this.templateType = templateType == null ? null : templateType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_msg_sms_log.bussiness_id
	 * @return  the value of t_msg_sms_log.bussiness_id
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	public String getBussinessId() {
		return bussinessId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_msg_sms_log.bussiness_id
	 * @param bussinessId  the value for t_msg_sms_log.bussiness_id
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	public void setBussinessId(String bussinessId) {
		this.bussinessId = bussinessId == null ? null : bussinessId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_msg_sms_log.member_name
	 * @return  the value of t_msg_sms_log.member_name
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	public String getMemberName() {
		return memberName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_msg_sms_log.member_name
	 * @param memberName  the value for t_msg_sms_log.member_name
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	public void setMemberName(String memberName) {
		this.memberName = memberName == null ? null : memberName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_msg_sms_log.member_phone
	 * @return  the value of t_msg_sms_log.member_phone
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	public String getMemberPhone() {
		return memberPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_msg_sms_log.member_phone
	 * @param memberPhone  the value for t_msg_sms_log.member_phone
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	public void setMemberPhone(String memberPhone) {
		this.memberPhone = memberPhone == null ? null : memberPhone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_msg_sms_log.result_info
	 * @return  the value of t_msg_sms_log.result_info
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	public String getResultInfo() {
		return resultInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_msg_sms_log.result_info
	 * @param resultInfo  the value for t_msg_sms_log.result_info
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	public void setResultInfo(String resultInfo) {
		this.resultInfo = resultInfo == null ? null : resultInfo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_msg_sms_log.send_state
	 * @return  the value of t_msg_sms_log.send_state
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	public Integer getSendState() {
		return sendState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_msg_sms_log.send_state
	 * @param sendState  the value for t_msg_sms_log.send_state
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	public void setSendState(Integer sendState) {
		this.sendState = sendState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_msg_sms_log.update_user_id
	 * @return  the value of t_msg_sms_log.update_user_id
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	public Integer getUpdateUserId() {
		return updateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_msg_sms_log.update_user_id
	 * @param updateUserId  the value for t_msg_sms_log.update_user_id
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	public void setUpdateUserId(Integer updateUserId) {
		this.updateUserId = updateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_msg_sms_log.update_date
	 * @return  the value of t_msg_sms_log.update_date
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_msg_sms_log.update_date
	 * @param updateDate  the value for t_msg_sms_log.update_date
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_msg_sms_log.create_user_id
	 * @return  the value of t_msg_sms_log.create_user_id
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	public Integer getCreateUserId() {
		return createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_msg_sms_log.create_user_id
	 * @param createUserId  the value for t_msg_sms_log.create_user_id
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_msg_sms_log.create_date
	 * @return  the value of t_msg_sms_log.create_date
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_msg_sms_log.create_date
	 * @param createDate  the value for t_msg_sms_log.create_date
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_msg_sms_log.message_body
	 * @return  the value of t_msg_sms_log.message_body
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	public String getMessageBody() {
		return messageBody;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_msg_sms_log.message_body
	 * @param messageBody  the value for t_msg_sms_log.message_body
	 * @mbg.generated  Fri Aug 31 15:27:57 CST 2018
	 */
	public void setMessageBody(String messageBody) {
		this.messageBody = messageBody == null ? null : messageBody.trim();
	}

	private String _id;

	//品牌id
	private Long sysBrandId;
	@io.swagger.annotations.ApiModelProperty(value = "品牌", name = "sysBrandId", required = false, example = "")
	private String templateTypeName;
	public String getTemplateTypeName() {
		return templateTypeName;
	}
	
	

	public String getResultInfoDetail() {
		return resultInfoDetail;
	}

	public void setResultInfoDetail(String resultInfoDetail) {
		this.resultInfoDetail = resultInfoDetail;
	}

	public void setTemplateTypeName(String templateTypeName) {
		this.templateTypeName = templateTypeName;
	}

	public String get_id() {
		return _id;
	}

	public void set_id(String _id) {
		this._id = _id;
	}

	public Long getSysBrandId() {
		return sysBrandId;
	}

	public void setSysBrandId(Long sysBrandId) {
		this.sysBrandId = sysBrandId;
	}
}