package com.bizvane.messagefacade.models.po;

import java.util.Date;

public class MsgVerifcodePO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg_verifcode.verifcode_id
     *
     * @mbg.generated Fri Aug 31 15:34:28 CST 2018
     */
    private Long verifcodeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg_verifcode.sys_company_id
     *
     * @mbg.generated Fri Aug 31 15:34:28 CST 2018
     */
    private Long sysCompanyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg_verifcode.phone
     *
     * @mbg.generated Fri Aug 31 15:34:28 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg_verifcode.verif_code
     *
     * @mbg.generated Fri Aug 31 15:34:28 CST 2018
     */
    private String verifCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg_verifcode.platform
     *
     * @mbg.generated Fri Aug 31 15:34:28 CST 2018
     */
    private String platform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg_verifcode.remark
     *
     * @mbg.generated Fri Aug 31 15:34:28 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg_verifcode.create_user_id
     *
     * @mbg.generated Fri Aug 31 15:34:28 CST 2018
     */
    private Long createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg_verifcode.create_user_name
     *
     * @mbg.generated Fri Aug 31 15:34:28 CST 2018
     */
    private String createUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg_verifcode.create_date
     *
     * @mbg.generated Fri Aug 31 15:34:28 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg_verifcode.modified_user_id
     *
     * @mbg.generated Fri Aug 31 15:34:28 CST 2018
     */
    private Long modifiedUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg_verifcode.modified_user_name
     *
     * @mbg.generated Fri Aug 31 15:34:28 CST 2018
     */
    private String modifiedUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg_verifcode.modified_date
     *
     * @mbg.generated Fri Aug 31 15:34:28 CST 2018
     */
    private Date modifiedDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_verifcode.verifcode_id
     *
     * @return the value of t_msg_verifcode.verifcode_id
     *
     * @mbg.generated Fri Aug 31 15:34:28 CST 2018
     */
    public Long getVerifcodeId() {
        return verifcodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_verifcode.verifcode_id
     *
     * @param verifcodeId the value for t_msg_verifcode.verifcode_id
     *
     * @mbg.generated Fri Aug 31 15:34:28 CST 2018
     */
    public void setVerifcodeId(Long verifcodeId) {
        this.verifcodeId = verifcodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_verifcode.sys_company_id
     *
     * @return the value of t_msg_verifcode.sys_company_id
     *
     * @mbg.generated Fri Aug 31 15:34:28 CST 2018
     */
    public Long getSysCompanyId() {
        return sysCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_verifcode.sys_company_id
     *
     * @param sysCompanyId the value for t_msg_verifcode.sys_company_id
     *
     * @mbg.generated Fri Aug 31 15:34:28 CST 2018
     */
    public void setSysCompanyId(Long sysCompanyId) {
        this.sysCompanyId = sysCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_verifcode.phone
     *
     * @return the value of t_msg_verifcode.phone
     *
     * @mbg.generated Fri Aug 31 15:34:28 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_verifcode.phone
     *
     * @param phone the value for t_msg_verifcode.phone
     *
     * @mbg.generated Fri Aug 31 15:34:28 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_verifcode.verif_code
     *
     * @return the value of t_msg_verifcode.verif_code
     *
     * @mbg.generated Fri Aug 31 15:34:28 CST 2018
     */
    public String getVerifCode() {
        return verifCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_verifcode.verif_code
     *
     * @param verifCode the value for t_msg_verifcode.verif_code
     *
     * @mbg.generated Fri Aug 31 15:34:28 CST 2018
     */
    public void setVerifCode(String verifCode) {
        this.verifCode = verifCode == null ? null : verifCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_verifcode.platform
     *
     * @return the value of t_msg_verifcode.platform
     *
     * @mbg.generated Fri Aug 31 15:34:28 CST 2018
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_verifcode.platform
     *
     * @param platform the value for t_msg_verifcode.platform
     *
     * @mbg.generated Fri Aug 31 15:34:28 CST 2018
     */
    public void setPlatform(String platform) {
        this.platform = platform == null ? null : platform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_verifcode.remark
     *
     * @return the value of t_msg_verifcode.remark
     *
     * @mbg.generated Fri Aug 31 15:34:28 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_verifcode.remark
     *
     * @param remark the value for t_msg_verifcode.remark
     *
     * @mbg.generated Fri Aug 31 15:34:28 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_verifcode.create_user_id
     *
     * @return the value of t_msg_verifcode.create_user_id
     *
     * @mbg.generated Fri Aug 31 15:34:28 CST 2018
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_verifcode.create_user_id
     *
     * @param createUserId the value for t_msg_verifcode.create_user_id
     *
     * @mbg.generated Fri Aug 31 15:34:28 CST 2018
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_verifcode.create_user_name
     *
     * @return the value of t_msg_verifcode.create_user_name
     *
     * @mbg.generated Fri Aug 31 15:34:28 CST 2018
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_verifcode.create_user_name
     *
     * @param createUserName the value for t_msg_verifcode.create_user_name
     *
     * @mbg.generated Fri Aug 31 15:34:28 CST 2018
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName == null ? null : createUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_verifcode.create_date
     *
     * @return the value of t_msg_verifcode.create_date
     *
     * @mbg.generated Fri Aug 31 15:34:28 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_verifcode.create_date
     *
     * @param createDate the value for t_msg_verifcode.create_date
     *
     * @mbg.generated Fri Aug 31 15:34:28 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_verifcode.modified_user_id
     *
     * @return the value of t_msg_verifcode.modified_user_id
     *
     * @mbg.generated Fri Aug 31 15:34:28 CST 2018
     */
    public Long getModifiedUserId() {
        return modifiedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_verifcode.modified_user_id
     *
     * @param modifiedUserId the value for t_msg_verifcode.modified_user_id
     *
     * @mbg.generated Fri Aug 31 15:34:28 CST 2018
     */
    public void setModifiedUserId(Long modifiedUserId) {
        this.modifiedUserId = modifiedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_verifcode.modified_user_name
     *
     * @return the value of t_msg_verifcode.modified_user_name
     *
     * @mbg.generated Fri Aug 31 15:34:28 CST 2018
     */
    public String getModifiedUserName() {
        return modifiedUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_verifcode.modified_user_name
     *
     * @param modifiedUserName the value for t_msg_verifcode.modified_user_name
     *
     * @mbg.generated Fri Aug 31 15:34:28 CST 2018
     */
    public void setModifiedUserName(String modifiedUserName) {
        this.modifiedUserName = modifiedUserName == null ? null : modifiedUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg_verifcode.modified_date
     *
     * @return the value of t_msg_verifcode.modified_date
     *
     * @mbg.generated Fri Aug 31 15:34:28 CST 2018
     */
    public Date getModifiedDate() {
        return modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg_verifcode.modified_date
     *
     * @param modifiedDate the value for t_msg_verifcode.modified_date
     *
     * @mbg.generated Fri Aug 31 15:34:28 CST 2018
     */
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
}