package com.bizvane.messagefacade.models.po;

import java.io.Serializable;
import java.util.Date;

public class MsgWxLogPO implements Serializable {
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_msg_wx_log.wechat_message_log_id
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	
	 private String _id;
	 
	@io.swagger.annotations.ApiModelProperty(value = "主键id", name = "wechatMessageLogId", required = false, example = "")
	private Long wechatMessageLogId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_msg_wx_log.sys_company_id
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	private Long sysCompanyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_msg_wx_log.rocket_msg_id
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	@io.swagger.annotations.ApiModelProperty(value = "消息队列msgid", name = "rocketMsgId", required = false, example = "")
	private String rocketMsgId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_msg_wx_log.message_id
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	@io.swagger.annotations.ApiModelProperty(value = "消息id", name = "messageId", required = false, example = "")
	private String messageId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_msg_wx_log.bussiness_module_code
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	@io.swagger.annotations.ApiModelProperty(value = "业务模型代码", name = "bussinessModuleCode", required = false, example = "")
	private String bussinessModuleCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_msg_wx_log.bussiness_id
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	@io.swagger.annotations.ApiModelProperty(value = "业务单据号", name = "bussinessId", required = false, example = "")
	private String bussinessId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_msg_wx_log.wx_public_id
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	@io.swagger.annotations.ApiModelProperty(value = "微信公众号id", name = "wxPublicId", required = false, example = "")
	private Long wxPublicId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_msg_wx_log.open_id
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	@io.swagger.annotations.ApiModelProperty(value = "会员openid", name = "openId", required = false, example = "")
	private String openId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_msg_wx_log.member_name
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	@io.swagger.annotations.ApiModelProperty(value = "会员姓名", name = "memberName", required = false, example = "")
	private String memberName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_msg_wx_log.member_phone
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	@io.swagger.annotations.ApiModelProperty(value = "会员手机号码", name = "memberPhone", required = false, example = "")
	private String memberPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_msg_wx_log.wx_nick
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	@io.swagger.annotations.ApiModelProperty(value = "微信昵称", name = "wxNick", required = false, example = "")
	private String wxNick;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_msg_wx_log.template_type
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	@io.swagger.annotations.ApiModelProperty(value = "微信模板类型(消息内容)", name = "templateType", required = false, example = "")
	private String templateType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_msg_wx_log.data_body
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	@io.swagger.annotations.ApiModelProperty(value = "发送数据", name = "dataBody", required = false, example = "")
	private String dataBody;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_msg_wx_log.message_body
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	@io.swagger.annotations.ApiModelProperty(value = "微信消息体(消息内容)", name = "messageBody", required = false, example = "")
	private String messageBody;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_msg_wx_log.result_info
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	@io.swagger.annotations.ApiModelProperty(value = "返回数据", name = "resultInfo", required = false, example = "")
	private String resultInfo;
	
	@io.swagger.annotations.ApiModelProperty(value = "返回数据明细信息", name = "resultInfoDetail", required = false, example = "")
	private String resultInfoDetail;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_msg_wx_log.send_state
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	@io.swagger.annotations.ApiModelProperty(value = "发送状态：00-新增；05-失败；10-成功；", name = "sendState", required = false, example = "")
	private String sendState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_msg_wx_log.is_resend
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	@io.swagger.annotations.ApiModelProperty(value = "出现错误是否支持重发", name = "isResend", required = false, example = "")
	private Boolean isResend;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_msg_wx_log.update_user_id
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	@io.swagger.annotations.ApiModelProperty(value = "最后修改人", name = "updateUserId", required = false, example = "")
	private Integer updateUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_msg_wx_log.update_date
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	@io.swagger.annotations.ApiModelProperty(value = "最后修改日期", name = "updateDate", required = false, example = "")
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_msg_wx_log.create_user_id
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	@io.swagger.annotations.ApiModelProperty(value = "创建人", name = "createUserId", required = false, example = "")
	private Integer createUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_msg_wx_log.create_date
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	@io.swagger.annotations.ApiModelProperty(value = "创建日期（发送时间）", name = "createDate", required = false, example = "")
	private Date createDate;
	
	
	//品牌id
	private Long sysBrandId;
	@io.swagger.annotations.ApiModelProperty(value = "品牌", name = "sysBrandId", required = false, example = "")
	
	
	

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_msg_wx_log.wechat_message_log_id
	 * @return  the value of t_msg_wx_log.wechat_message_log_id
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public Long getWechatMessageLogId() {
		return wechatMessageLogId;
	}

	public String getResultInfoDetail() {
		return resultInfoDetail;
	}

	public void setResultInfoDetail(String resultInfoDetail) {
		this.resultInfoDetail = resultInfoDetail;
	}

	public Long getSysBrandId() {
		return sysBrandId;
	}

	public void setSysBrandId(Long sysBrandId) {
		this.sysBrandId = sysBrandId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_msg_wx_log.wechat_message_log_id
	 * @param wechatMessageLogId  the value for t_msg_wx_log.wechat_message_log_id
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public void setWechatMessageLogId(Long wechatMessageLogId) {
		this.wechatMessageLogId = wechatMessageLogId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_msg_wx_log.sys_company_id
	 * @return  the value of t_msg_wx_log.sys_company_id
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public Long getSysCompanyId() {
		return sysCompanyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_msg_wx_log.sys_company_id
	 * @param sysCompanyId  the value for t_msg_wx_log.sys_company_id
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public void setSysCompanyId(Long sysCompanyId) {
		this.sysCompanyId = sysCompanyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_msg_wx_log.rocket_msg_id
	 * @return  the value of t_msg_wx_log.rocket_msg_id
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public String getRocketMsgId() {
		return rocketMsgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_msg_wx_log.rocket_msg_id
	 * @param rocketMsgId  the value for t_msg_wx_log.rocket_msg_id
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public void setRocketMsgId(String rocketMsgId) {
		this.rocketMsgId = rocketMsgId == null ? null : rocketMsgId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_msg_wx_log.message_id
	 * @return  the value of t_msg_wx_log.message_id
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public String getMessageId() {
		return messageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_msg_wx_log.message_id
	 * @param messageId  the value for t_msg_wx_log.message_id
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public void setMessageId(String messageId) {
		this.messageId = messageId == null ? null : messageId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_msg_wx_log.bussiness_module_code
	 * @return  the value of t_msg_wx_log.bussiness_module_code
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public String getBussinessModuleCode() {
		return bussinessModuleCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_msg_wx_log.bussiness_module_code
	 * @param bussinessModuleCode  the value for t_msg_wx_log.bussiness_module_code
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public void setBussinessModuleCode(String bussinessModuleCode) {
		this.bussinessModuleCode = bussinessModuleCode == null ? null : bussinessModuleCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_msg_wx_log.bussiness_id
	 * @return  the value of t_msg_wx_log.bussiness_id
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public String getBussinessId() {
		return bussinessId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_msg_wx_log.bussiness_id
	 * @param bussinessId  the value for t_msg_wx_log.bussiness_id
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public void setBussinessId(String bussinessId) {
		this.bussinessId = bussinessId == null ? null : bussinessId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_msg_wx_log.wx_public_id
	 * @return  the value of t_msg_wx_log.wx_public_id
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public Long getWxPublicId() {
		return wxPublicId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_msg_wx_log.wx_public_id
	 * @param wxPublicId  the value for t_msg_wx_log.wx_public_id
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public void setWxPublicId(Long wxPublicId) {
		this.wxPublicId = wxPublicId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_msg_wx_log.open_id
	 * @return  the value of t_msg_wx_log.open_id
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public String getOpenId() {
		return openId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_msg_wx_log.open_id
	 * @param openId  the value for t_msg_wx_log.open_id
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public void setOpenId(String openId) {
		this.openId = openId == null ? null : openId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_msg_wx_log.member_name
	 * @return  the value of t_msg_wx_log.member_name
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public String getMemberName() {
		return memberName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_msg_wx_log.member_name
	 * @param memberName  the value for t_msg_wx_log.member_name
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public void setMemberName(String memberName) {
		this.memberName = memberName == null ? null : memberName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_msg_wx_log.member_phone
	 * @return  the value of t_msg_wx_log.member_phone
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public String getMemberPhone() {
		return memberPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_msg_wx_log.member_phone
	 * @param memberPhone  the value for t_msg_wx_log.member_phone
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public void setMemberPhone(String memberPhone) {
		this.memberPhone = memberPhone == null ? null : memberPhone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_msg_wx_log.wx_nick
	 * @return  the value of t_msg_wx_log.wx_nick
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public String getWxNick() {
		return wxNick;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_msg_wx_log.wx_nick
	 * @param wxNick  the value for t_msg_wx_log.wx_nick
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public void setWxNick(String wxNick) {
		this.wxNick = wxNick == null ? null : wxNick.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_msg_wx_log.template_type
	 * @return  the value of t_msg_wx_log.template_type
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public String getTemplateType() {
		return templateType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_msg_wx_log.template_type
	 * @param templateType  the value for t_msg_wx_log.template_type
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public void setTemplateType(String templateType) {
		this.templateType = templateType == null ? null : templateType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_msg_wx_log.data_body
	 * @return  the value of t_msg_wx_log.data_body
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public String getDataBody() {
		return dataBody;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_msg_wx_log.data_body
	 * @param dataBody  the value for t_msg_wx_log.data_body
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public void setDataBody(String dataBody) {
		this.dataBody = dataBody == null ? null : dataBody.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_msg_wx_log.message_body
	 * @return  the value of t_msg_wx_log.message_body
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public String getMessageBody() {
		return messageBody;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_msg_wx_log.message_body
	 * @param messageBody  the value for t_msg_wx_log.message_body
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public void setMessageBody(String messageBody) {
		this.messageBody = messageBody == null ? null : messageBody.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_msg_wx_log.result_info
	 * @return  the value of t_msg_wx_log.result_info
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public String getResultInfo() {
		return resultInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_msg_wx_log.result_info
	 * @param resultInfo  the value for t_msg_wx_log.result_info
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public void setResultInfo(String resultInfo) {
		this.resultInfo = resultInfo == null ? null : resultInfo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_msg_wx_log.send_state
	 * @return  the value of t_msg_wx_log.send_state
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public String getSendState() {
		return sendState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_msg_wx_log.send_state
	 * @param sendState  the value for t_msg_wx_log.send_state
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public void setSendState(String sendState) {
		this.sendState = sendState == null ? null : sendState.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_msg_wx_log.is_resend
	 * @return  the value of t_msg_wx_log.is_resend
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public Boolean getIsResend() {
		return isResend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_msg_wx_log.is_resend
	 * @param isResend  the value for t_msg_wx_log.is_resend
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public void setIsResend(Boolean isResend) {
		this.isResend = isResend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_msg_wx_log.update_user_id
	 * @return  the value of t_msg_wx_log.update_user_id
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public Integer getUpdateUserId() {
		return updateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_msg_wx_log.update_user_id
	 * @param updateUserId  the value for t_msg_wx_log.update_user_id
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public void setUpdateUserId(Integer updateUserId) {
		this.updateUserId = updateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_msg_wx_log.update_date
	 * @return  the value of t_msg_wx_log.update_date
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_msg_wx_log.update_date
	 * @param updateDate  the value for t_msg_wx_log.update_date
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_msg_wx_log.create_user_id
	 * @return  the value of t_msg_wx_log.create_user_id
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public Integer getCreateUserId() {
		return createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_msg_wx_log.create_user_id
	 * @param createUserId  the value for t_msg_wx_log.create_user_id
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_msg_wx_log.create_date
	 * @return  the value of t_msg_wx_log.create_date
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_msg_wx_log.create_date
	 * @param createDate  the value for t_msg_wx_log.create_date
	 * @mbg.generated  Fri Aug 31 15:35:26 CST 2018
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@io.swagger.annotations.ApiModelProperty(value = "微信模板类型",name = "templateTypeName", required = false,example = "")
    private String templateTypeName;

    public String getTemplateTypeName() {
		return templateTypeName;
	}

	public void setTemplateTypeName(String templateTypeName) {
		this.templateTypeName = templateTypeName;
	}

	public String get_id() {
		return _id;
	}

	public void set_id(String _id) {
		this._id = _id;
	}
    
    
}