package com.bizvane.messagefacade.models.po;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysSmsConfigPOExample implements Serializable {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_sys_sms_config
	 * @mbg.generated  Mon Aug 20 20:07:00 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_sys_sms_config
	 * @mbg.generated  Mon Aug 20 20:07:00 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_sys_sms_config
	 * @mbg.generated  Mon Aug 20 20:07:00 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_sms_config
	 * @mbg.generated  Mon Aug 20 20:07:00 CST 2018
	 */
	public SysSmsConfigPOExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_sms_config
	 * @mbg.generated  Mon Aug 20 20:07:00 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_sms_config
	 * @mbg.generated  Mon Aug 20 20:07:00 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_sms_config
	 * @mbg.generated  Mon Aug 20 20:07:00 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_sms_config
	 * @mbg.generated  Mon Aug 20 20:07:00 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_sms_config
	 * @mbg.generated  Mon Aug 20 20:07:00 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_sms_config
	 * @mbg.generated  Mon Aug 20 20:07:00 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_sms_config
	 * @mbg.generated  Mon Aug 20 20:07:00 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_sms_config
	 * @mbg.generated  Mon Aug 20 20:07:00 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_sms_config
	 * @mbg.generated  Mon Aug 20 20:07:00 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_sms_config
	 * @mbg.generated  Mon Aug 20 20:07:00 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_sys_sms_config
	 * @mbg.generated  Mon Aug 20 20:07:00 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andSysSmsConfigIdIsNull() {
			addCriterion("sys_sms_config_id is null");
			return (Criteria) this;
		}

		public Criteria andSysSmsConfigIdIsNotNull() {
			addCriterion("sys_sms_config_id is not null");
			return (Criteria) this;
		}

		public Criteria andSysSmsConfigIdEqualTo(Long value) {
			addCriterion("sys_sms_config_id =", value, "sysSmsConfigId");
			return (Criteria) this;
		}

		public Criteria andSysSmsConfigIdNotEqualTo(Long value) {
			addCriterion("sys_sms_config_id <>", value, "sysSmsConfigId");
			return (Criteria) this;
		}

		public Criteria andSysSmsConfigIdGreaterThan(Long value) {
			addCriterion("sys_sms_config_id >", value, "sysSmsConfigId");
			return (Criteria) this;
		}

		public Criteria andSysSmsConfigIdGreaterThanOrEqualTo(Long value) {
			addCriterion("sys_sms_config_id >=", value, "sysSmsConfigId");
			return (Criteria) this;
		}

		public Criteria andSysSmsConfigIdLessThan(Long value) {
			addCriterion("sys_sms_config_id <", value, "sysSmsConfigId");
			return (Criteria) this;
		}

		public Criteria andSysSmsConfigIdLessThanOrEqualTo(Long value) {
			addCriterion("sys_sms_config_id <=", value, "sysSmsConfigId");
			return (Criteria) this;
		}

		public Criteria andSysSmsConfigIdIn(List<Long> values) {
			addCriterion("sys_sms_config_id in", values, "sysSmsConfigId");
			return (Criteria) this;
		}

		public Criteria andSysSmsConfigIdNotIn(List<Long> values) {
			addCriterion("sys_sms_config_id not in", values, "sysSmsConfigId");
			return (Criteria) this;
		}

		public Criteria andSysSmsConfigIdBetween(Long value1, Long value2) {
			addCriterion("sys_sms_config_id between", value1, value2, "sysSmsConfigId");
			return (Criteria) this;
		}

		public Criteria andSysSmsConfigIdNotBetween(Long value1, Long value2) {
			addCriterion("sys_sms_config_id not between", value1, value2, "sysSmsConfigId");
			return (Criteria) this;
		}

		public Criteria andSysCompanyIdIsNull() {
			addCriterion("sys_company_id is null");
			return (Criteria) this;
		}

		public Criteria andSysCompanyIdIsNotNull() {
			addCriterion("sys_company_id is not null");
			return (Criteria) this;
		}

		public Criteria andSysCompanyIdEqualTo(String value) {
			addCriterion("sys_company_id =", value, "sysCompanyId");
			return (Criteria) this;
		}

		public Criteria andSysCompanyIdNotEqualTo(String value) {
			addCriterion("sys_company_id <>", value, "sysCompanyId");
			return (Criteria) this;
		}

		public Criteria andSysCompanyIdGreaterThan(String value) {
			addCriterion("sys_company_id >", value, "sysCompanyId");
			return (Criteria) this;
		}

		public Criteria andSysCompanyIdGreaterThanOrEqualTo(String value) {
			addCriterion("sys_company_id >=", value, "sysCompanyId");
			return (Criteria) this;
		}

		public Criteria andSysCompanyIdLessThan(String value) {
			addCriterion("sys_company_id <", value, "sysCompanyId");
			return (Criteria) this;
		}

		public Criteria andSysCompanyIdLessThanOrEqualTo(String value) {
			addCriterion("sys_company_id <=", value, "sysCompanyId");
			return (Criteria) this;
		}

		public Criteria andSysCompanyIdLike(String value) {
			addCriterion("sys_company_id like", value, "sysCompanyId");
			return (Criteria) this;
		}

		public Criteria andSysCompanyIdNotLike(String value) {
			addCriterion("sys_company_id not like", value, "sysCompanyId");
			return (Criteria) this;
		}

		public Criteria andSysCompanyIdIn(List<String> values) {
			addCriterion("sys_company_id in", values, "sysCompanyId");
			return (Criteria) this;
		}

		public Criteria andSysCompanyIdNotIn(List<String> values) {
			addCriterion("sys_company_id not in", values, "sysCompanyId");
			return (Criteria) this;
		}

		public Criteria andSysCompanyIdBetween(String value1, String value2) {
			addCriterion("sys_company_id between", value1, value2, "sysCompanyId");
			return (Criteria) this;
		}

		public Criteria andSysCompanyIdNotBetween(String value1, String value2) {
			addCriterion("sys_company_id not between", value1, value2, "sysCompanyId");
			return (Criteria) this;
		}

		public Criteria andCompanyCodeIsNull() {
			addCriterion("company_code is null");
			return (Criteria) this;
		}

		public Criteria andCompanyCodeIsNotNull() {
			addCriterion("company_code is not null");
			return (Criteria) this;
		}

		public Criteria andCompanyCodeEqualTo(String value) {
			addCriterion("company_code =", value, "companyCode");
			return (Criteria) this;
		}

		public Criteria andCompanyCodeNotEqualTo(String value) {
			addCriterion("company_code <>", value, "companyCode");
			return (Criteria) this;
		}

		public Criteria andCompanyCodeGreaterThan(String value) {
			addCriterion("company_code >", value, "companyCode");
			return (Criteria) this;
		}

		public Criteria andCompanyCodeGreaterThanOrEqualTo(String value) {
			addCriterion("company_code >=", value, "companyCode");
			return (Criteria) this;
		}

		public Criteria andCompanyCodeLessThan(String value) {
			addCriterion("company_code <", value, "companyCode");
			return (Criteria) this;
		}

		public Criteria andCompanyCodeLessThanOrEqualTo(String value) {
			addCriterion("company_code <=", value, "companyCode");
			return (Criteria) this;
		}

		public Criteria andCompanyCodeLike(String value) {
			addCriterion("company_code like", value, "companyCode");
			return (Criteria) this;
		}

		public Criteria andCompanyCodeNotLike(String value) {
			addCriterion("company_code not like", value, "companyCode");
			return (Criteria) this;
		}

		public Criteria andCompanyCodeIn(List<String> values) {
			addCriterion("company_code in", values, "companyCode");
			return (Criteria) this;
		}

		public Criteria andCompanyCodeNotIn(List<String> values) {
			addCriterion("company_code not in", values, "companyCode");
			return (Criteria) this;
		}

		public Criteria andCompanyCodeBetween(String value1, String value2) {
			addCriterion("company_code between", value1, value2, "companyCode");
			return (Criteria) this;
		}

		public Criteria andCompanyCodeNotBetween(String value1, String value2) {
			addCriterion("company_code not between", value1, value2, "companyCode");
			return (Criteria) this;
		}

		public Criteria andCompanyNameIsNull() {
			addCriterion("company_name is null");
			return (Criteria) this;
		}

		public Criteria andCompanyNameIsNotNull() {
			addCriterion("company_name is not null");
			return (Criteria) this;
		}

		public Criteria andCompanyNameEqualTo(String value) {
			addCriterion("company_name =", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameNotEqualTo(String value) {
			addCriterion("company_name <>", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameGreaterThan(String value) {
			addCriterion("company_name >", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameGreaterThanOrEqualTo(String value) {
			addCriterion("company_name >=", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameLessThan(String value) {
			addCriterion("company_name <", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameLessThanOrEqualTo(String value) {
			addCriterion("company_name <=", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameLike(String value) {
			addCriterion("company_name like", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameNotLike(String value) {
			addCriterion("company_name not like", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameIn(List<String> values) {
			addCriterion("company_name in", values, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameNotIn(List<String> values) {
			addCriterion("company_name not in", values, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameBetween(String value1, String value2) {
			addCriterion("company_name between", value1, value2, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameNotBetween(String value1, String value2) {
			addCriterion("company_name not between", value1, value2, "companyName");
			return (Criteria) this;
		}

		public Criteria andSysBrandIdIsNull() {
			addCriterion("sys_brand_id is null");
			return (Criteria) this;
		}

		public Criteria andSysBrandIdIsNotNull() {
			addCriterion("sys_brand_id is not null");
			return (Criteria) this;
		}

		public Criteria andSysBrandIdEqualTo(Long value) {
			addCriterion("sys_brand_id =", value, "sysBrandId");
			return (Criteria) this;
		}

		public Criteria andSysBrandIdNotEqualTo(Long value) {
			addCriterion("sys_brand_id <>", value, "sysBrandId");
			return (Criteria) this;
		}

		public Criteria andSysBrandIdGreaterThan(Long value) {
			addCriterion("sys_brand_id >", value, "sysBrandId");
			return (Criteria) this;
		}

		public Criteria andSysBrandIdGreaterThanOrEqualTo(Long value) {
			addCriterion("sys_brand_id >=", value, "sysBrandId");
			return (Criteria) this;
		}

		public Criteria andSysBrandIdLessThan(Long value) {
			addCriterion("sys_brand_id <", value, "sysBrandId");
			return (Criteria) this;
		}

		public Criteria andSysBrandIdLessThanOrEqualTo(Long value) {
			addCriterion("sys_brand_id <=", value, "sysBrandId");
			return (Criteria) this;
		}

		public Criteria andSysBrandIdIn(List<Long> values) {
			addCriterion("sys_brand_id in", values, "sysBrandId");
			return (Criteria) this;
		}

		public Criteria andSysBrandIdNotIn(List<Long> values) {
			addCriterion("sys_brand_id not in", values, "sysBrandId");
			return (Criteria) this;
		}

		public Criteria andSysBrandIdBetween(Long value1, Long value2) {
			addCriterion("sys_brand_id between", value1, value2, "sysBrandId");
			return (Criteria) this;
		}

		public Criteria andSysBrandIdNotBetween(Long value1, Long value2) {
			addCriterion("sys_brand_id not between", value1, value2, "sysBrandId");
			return (Criteria) this;
		}

		public Criteria andBrandNameIsNull() {
			addCriterion("brand_name is null");
			return (Criteria) this;
		}

		public Criteria andBrandNameIsNotNull() {
			addCriterion("brand_name is not null");
			return (Criteria) this;
		}

		public Criteria andBrandNameEqualTo(String value) {
			addCriterion("brand_name =", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameNotEqualTo(String value) {
			addCriterion("brand_name <>", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameGreaterThan(String value) {
			addCriterion("brand_name >", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameGreaterThanOrEqualTo(String value) {
			addCriterion("brand_name >=", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameLessThan(String value) {
			addCriterion("brand_name <", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameLessThanOrEqualTo(String value) {
			addCriterion("brand_name <=", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameLike(String value) {
			addCriterion("brand_name like", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameNotLike(String value) {
			addCriterion("brand_name not like", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameIn(List<String> values) {
			addCriterion("brand_name in", values, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameNotIn(List<String> values) {
			addCriterion("brand_name not in", values, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameBetween(String value1, String value2) {
			addCriterion("brand_name between", value1, value2, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameNotBetween(String value1, String value2) {
			addCriterion("brand_name not between", value1, value2, "brandName");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeIsNull() {
			addCriterion("platform_type is null");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeIsNotNull() {
			addCriterion("platform_type is not null");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeEqualTo(Integer value) {
			addCriterion("platform_type =", value, "platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeNotEqualTo(Integer value) {
			addCriterion("platform_type <>", value, "platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeGreaterThan(Integer value) {
			addCriterion("platform_type >", value, "platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("platform_type >=", value, "platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeLessThan(Integer value) {
			addCriterion("platform_type <", value, "platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeLessThanOrEqualTo(Integer value) {
			addCriterion("platform_type <=", value, "platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeIn(List<Integer> values) {
			addCriterion("platform_type in", values, "platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeNotIn(List<Integer> values) {
			addCriterion("platform_type not in", values, "platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeBetween(Integer value1, Integer value2) {
			addCriterion("platform_type between", value1, value2, "platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("platform_type not between", value1, value2, "platformType");
			return (Criteria) this;
		}

		public Criteria andChannelTypeIsNull() {
			addCriterion("channel_type is null");
			return (Criteria) this;
		}

		public Criteria andChannelTypeIsNotNull() {
			addCriterion("channel_type is not null");
			return (Criteria) this;
		}

		public Criteria andChannelTypeEqualTo(Integer value) {
			addCriterion("channel_type =", value, "channelType");
			return (Criteria) this;
		}

		public Criteria andChannelTypeNotEqualTo(Integer value) {
			addCriterion("channel_type <>", value, "channelType");
			return (Criteria) this;
		}

		public Criteria andChannelTypeGreaterThan(Integer value) {
			addCriterion("channel_type >", value, "channelType");
			return (Criteria) this;
		}

		public Criteria andChannelTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("channel_type >=", value, "channelType");
			return (Criteria) this;
		}

		public Criteria andChannelTypeLessThan(Integer value) {
			addCriterion("channel_type <", value, "channelType");
			return (Criteria) this;
		}

		public Criteria andChannelTypeLessThanOrEqualTo(Integer value) {
			addCriterion("channel_type <=", value, "channelType");
			return (Criteria) this;
		}

		public Criteria andChannelTypeIn(List<Integer> values) {
			addCriterion("channel_type in", values, "channelType");
			return (Criteria) this;
		}

		public Criteria andChannelTypeNotIn(List<Integer> values) {
			addCriterion("channel_type not in", values, "channelType");
			return (Criteria) this;
		}

		public Criteria andChannelTypeBetween(Integer value1, Integer value2) {
			addCriterion("channel_type between", value1, value2, "channelType");
			return (Criteria) this;
		}

		public Criteria andChannelTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("channel_type not between", value1, value2, "channelType");
			return (Criteria) this;
		}

		public Criteria andChannelIsNull() {
			addCriterion("channel is null");
			return (Criteria) this;
		}

		public Criteria andChannelIsNotNull() {
			addCriterion("channel is not null");
			return (Criteria) this;
		}

		public Criteria andChannelEqualTo(Integer value) {
			addCriterion("channel =", value, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelNotEqualTo(Integer value) {
			addCriterion("channel <>", value, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelGreaterThan(Integer value) {
			addCriterion("channel >", value, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelGreaterThanOrEqualTo(Integer value) {
			addCriterion("channel >=", value, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelLessThan(Integer value) {
			addCriterion("channel <", value, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelLessThanOrEqualTo(Integer value) {
			addCriterion("channel <=", value, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelIn(List<Integer> values) {
			addCriterion("channel in", values, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelNotIn(List<Integer> values) {
			addCriterion("channel not in", values, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelBetween(Integer value1, Integer value2) {
			addCriterion("channel between", value1, value2, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelNotBetween(Integer value1, Integer value2) {
			addCriterion("channel not between", value1, value2, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelNameIsNull() {
			addCriterion("channel_name is null");
			return (Criteria) this;
		}

		public Criteria andChannelNameIsNotNull() {
			addCriterion("channel_name is not null");
			return (Criteria) this;
		}

		public Criteria andChannelNameEqualTo(String value) {
			addCriterion("channel_name =", value, "channelName");
			return (Criteria) this;
		}

		public Criteria andChannelNameNotEqualTo(String value) {
			addCriterion("channel_name <>", value, "channelName");
			return (Criteria) this;
		}

		public Criteria andChannelNameGreaterThan(String value) {
			addCriterion("channel_name >", value, "channelName");
			return (Criteria) this;
		}

		public Criteria andChannelNameGreaterThanOrEqualTo(String value) {
			addCriterion("channel_name >=", value, "channelName");
			return (Criteria) this;
		}

		public Criteria andChannelNameLessThan(String value) {
			addCriterion("channel_name <", value, "channelName");
			return (Criteria) this;
		}

		public Criteria andChannelNameLessThanOrEqualTo(String value) {
			addCriterion("channel_name <=", value, "channelName");
			return (Criteria) this;
		}

		public Criteria andChannelNameLike(String value) {
			addCriterion("channel_name like", value, "channelName");
			return (Criteria) this;
		}

		public Criteria andChannelNameNotLike(String value) {
			addCriterion("channel_name not like", value, "channelName");
			return (Criteria) this;
		}

		public Criteria andChannelNameIn(List<String> values) {
			addCriterion("channel_name in", values, "channelName");
			return (Criteria) this;
		}

		public Criteria andChannelNameNotIn(List<String> values) {
			addCriterion("channel_name not in", values, "channelName");
			return (Criteria) this;
		}

		public Criteria andChannelNameBetween(String value1, String value2) {
			addCriterion("channel_name between", value1, value2, "channelName");
			return (Criteria) this;
		}

		public Criteria andChannelNameNotBetween(String value1, String value2) {
			addCriterion("channel_name not between", value1, value2, "channelName");
			return (Criteria) this;
		}

		public Criteria andChannelServiceIsNull() {
			addCriterion("channel_service is null");
			return (Criteria) this;
		}

		public Criteria andChannelServiceIsNotNull() {
			addCriterion("channel_service is not null");
			return (Criteria) this;
		}

		public Criteria andChannelServiceEqualTo(String value) {
			addCriterion("channel_service =", value, "channelService");
			return (Criteria) this;
		}

		public Criteria andChannelServiceNotEqualTo(String value) {
			addCriterion("channel_service <>", value, "channelService");
			return (Criteria) this;
		}

		public Criteria andChannelServiceGreaterThan(String value) {
			addCriterion("channel_service >", value, "channelService");
			return (Criteria) this;
		}

		public Criteria andChannelServiceGreaterThanOrEqualTo(String value) {
			addCriterion("channel_service >=", value, "channelService");
			return (Criteria) this;
		}

		public Criteria andChannelServiceLessThan(String value) {
			addCriterion("channel_service <", value, "channelService");
			return (Criteria) this;
		}

		public Criteria andChannelServiceLessThanOrEqualTo(String value) {
			addCriterion("channel_service <=", value, "channelService");
			return (Criteria) this;
		}

		public Criteria andChannelServiceLike(String value) {
			addCriterion("channel_service like", value, "channelService");
			return (Criteria) this;
		}

		public Criteria andChannelServiceNotLike(String value) {
			addCriterion("channel_service not like", value, "channelService");
			return (Criteria) this;
		}

		public Criteria andChannelServiceIn(List<String> values) {
			addCriterion("channel_service in", values, "channelService");
			return (Criteria) this;
		}

		public Criteria andChannelServiceNotIn(List<String> values) {
			addCriterion("channel_service not in", values, "channelService");
			return (Criteria) this;
		}

		public Criteria andChannelServiceBetween(String value1, String value2) {
			addCriterion("channel_service between", value1, value2, "channelService");
			return (Criteria) this;
		}

		public Criteria andChannelServiceNotBetween(String value1, String value2) {
			addCriterion("channel_service not between", value1, value2, "channelService");
			return (Criteria) this;
		}

		public Criteria andBatchChannelServiceIsNull() {
			addCriterion("batch_channel_service is null");
			return (Criteria) this;
		}

		public Criteria andBatchChannelServiceIsNotNull() {
			addCriterion("batch_channel_service is not null");
			return (Criteria) this;
		}

		public Criteria andBatchChannelServiceEqualTo(String value) {
			addCriterion("batch_channel_service =", value, "batchChannelService");
			return (Criteria) this;
		}

		public Criteria andBatchChannelServiceNotEqualTo(String value) {
			addCriterion("batch_channel_service <>", value, "batchChannelService");
			return (Criteria) this;
		}

		public Criteria andBatchChannelServiceGreaterThan(String value) {
			addCriterion("batch_channel_service >", value, "batchChannelService");
			return (Criteria) this;
		}

		public Criteria andBatchChannelServiceGreaterThanOrEqualTo(String value) {
			addCriterion("batch_channel_service >=", value, "batchChannelService");
			return (Criteria) this;
		}

		public Criteria andBatchChannelServiceLessThan(String value) {
			addCriterion("batch_channel_service <", value, "batchChannelService");
			return (Criteria) this;
		}

		public Criteria andBatchChannelServiceLessThanOrEqualTo(String value) {
			addCriterion("batch_channel_service <=", value, "batchChannelService");
			return (Criteria) this;
		}

		public Criteria andBatchChannelServiceLike(String value) {
			addCriterion("batch_channel_service like", value, "batchChannelService");
			return (Criteria) this;
		}

		public Criteria andBatchChannelServiceNotLike(String value) {
			addCriterion("batch_channel_service not like", value, "batchChannelService");
			return (Criteria) this;
		}

		public Criteria andBatchChannelServiceIn(List<String> values) {
			addCriterion("batch_channel_service in", values, "batchChannelService");
			return (Criteria) this;
		}

		public Criteria andBatchChannelServiceNotIn(List<String> values) {
			addCriterion("batch_channel_service not in", values, "batchChannelService");
			return (Criteria) this;
		}

		public Criteria andBatchChannelServiceBetween(String value1, String value2) {
			addCriterion("batch_channel_service between", value1, value2, "batchChannelService");
			return (Criteria) this;
		}

		public Criteria andBatchChannelServiceNotBetween(String value1, String value2) {
			addCriterion("batch_channel_service not between", value1, value2, "batchChannelService");
			return (Criteria) this;
		}

		public Criteria andChannelAccountIsNull() {
			addCriterion("channel_account is null");
			return (Criteria) this;
		}

		public Criteria andChannelAccountIsNotNull() {
			addCriterion("channel_account is not null");
			return (Criteria) this;
		}

		public Criteria andChannelAccountEqualTo(String value) {
			addCriterion("channel_account =", value, "channelAccount");
			return (Criteria) this;
		}

		public Criteria andChannelAccountNotEqualTo(String value) {
			addCriterion("channel_account <>", value, "channelAccount");
			return (Criteria) this;
		}

		public Criteria andChannelAccountGreaterThan(String value) {
			addCriterion("channel_account >", value, "channelAccount");
			return (Criteria) this;
		}

		public Criteria andChannelAccountGreaterThanOrEqualTo(String value) {
			addCriterion("channel_account >=", value, "channelAccount");
			return (Criteria) this;
		}

		public Criteria andChannelAccountLessThan(String value) {
			addCriterion("channel_account <", value, "channelAccount");
			return (Criteria) this;
		}

		public Criteria andChannelAccountLessThanOrEqualTo(String value) {
			addCriterion("channel_account <=", value, "channelAccount");
			return (Criteria) this;
		}

		public Criteria andChannelAccountLike(String value) {
			addCriterion("channel_account like", value, "channelAccount");
			return (Criteria) this;
		}

		public Criteria andChannelAccountNotLike(String value) {
			addCriterion("channel_account not like", value, "channelAccount");
			return (Criteria) this;
		}

		public Criteria andChannelAccountIn(List<String> values) {
			addCriterion("channel_account in", values, "channelAccount");
			return (Criteria) this;
		}

		public Criteria andChannelAccountNotIn(List<String> values) {
			addCriterion("channel_account not in", values, "channelAccount");
			return (Criteria) this;
		}

		public Criteria andChannelAccountBetween(String value1, String value2) {
			addCriterion("channel_account between", value1, value2, "channelAccount");
			return (Criteria) this;
		}

		public Criteria andChannelAccountNotBetween(String value1, String value2) {
			addCriterion("channel_account not between", value1, value2, "channelAccount");
			return (Criteria) this;
		}

		public Criteria andChannelPasswordIsNull() {
			addCriterion("channel_password is null");
			return (Criteria) this;
		}

		public Criteria andChannelPasswordIsNotNull() {
			addCriterion("channel_password is not null");
			return (Criteria) this;
		}

		public Criteria andChannelPasswordEqualTo(String value) {
			addCriterion("channel_password =", value, "channelPassword");
			return (Criteria) this;
		}

		public Criteria andChannelPasswordNotEqualTo(String value) {
			addCriterion("channel_password <>", value, "channelPassword");
			return (Criteria) this;
		}

		public Criteria andChannelPasswordGreaterThan(String value) {
			addCriterion("channel_password >", value, "channelPassword");
			return (Criteria) this;
		}

		public Criteria andChannelPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("channel_password >=", value, "channelPassword");
			return (Criteria) this;
		}

		public Criteria andChannelPasswordLessThan(String value) {
			addCriterion("channel_password <", value, "channelPassword");
			return (Criteria) this;
		}

		public Criteria andChannelPasswordLessThanOrEqualTo(String value) {
			addCriterion("channel_password <=", value, "channelPassword");
			return (Criteria) this;
		}

		public Criteria andChannelPasswordLike(String value) {
			addCriterion("channel_password like", value, "channelPassword");
			return (Criteria) this;
		}

		public Criteria andChannelPasswordNotLike(String value) {
			addCriterion("channel_password not like", value, "channelPassword");
			return (Criteria) this;
		}

		public Criteria andChannelPasswordIn(List<String> values) {
			addCriterion("channel_password in", values, "channelPassword");
			return (Criteria) this;
		}

		public Criteria andChannelPasswordNotIn(List<String> values) {
			addCriterion("channel_password not in", values, "channelPassword");
			return (Criteria) this;
		}

		public Criteria andChannelPasswordBetween(String value1, String value2) {
			addCriterion("channel_password between", value1, value2, "channelPassword");
			return (Criteria) this;
		}

		public Criteria andChannelPasswordNotBetween(String value1, String value2) {
			addCriterion("channel_password not between", value1, value2, "channelPassword");
			return (Criteria) this;
		}

		public Criteria andPriceIsNull() {
			addCriterion("price is null");
			return (Criteria) this;
		}

		public Criteria andPriceIsNotNull() {
			addCriterion("price is not null");
			return (Criteria) this;
		}

		public Criteria andPriceEqualTo(Long value) {
			addCriterion("price =", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotEqualTo(Long value) {
			addCriterion("price <>", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThan(Long value) {
			addCriterion("price >", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThanOrEqualTo(Long value) {
			addCriterion("price >=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThan(Long value) {
			addCriterion("price <", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThanOrEqualTo(Long value) {
			addCriterion("price <=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceIn(List<Long> values) {
			addCriterion("price in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotIn(List<Long> values) {
			addCriterion("price not in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceBetween(Long value1, Long value2) {
			addCriterion("price between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotBetween(Long value1, Long value2) {
			addCriterion("price not between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andBatchNumIsNull() {
			addCriterion("batch_num is null");
			return (Criteria) this;
		}

		public Criteria andBatchNumIsNotNull() {
			addCriterion("batch_num is not null");
			return (Criteria) this;
		}

		public Criteria andBatchNumEqualTo(Integer value) {
			addCriterion("batch_num =", value, "batchNum");
			return (Criteria) this;
		}

		public Criteria andBatchNumNotEqualTo(Integer value) {
			addCriterion("batch_num <>", value, "batchNum");
			return (Criteria) this;
		}

		public Criteria andBatchNumGreaterThan(Integer value) {
			addCriterion("batch_num >", value, "batchNum");
			return (Criteria) this;
		}

		public Criteria andBatchNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("batch_num >=", value, "batchNum");
			return (Criteria) this;
		}

		public Criteria andBatchNumLessThan(Integer value) {
			addCriterion("batch_num <", value, "batchNum");
			return (Criteria) this;
		}

		public Criteria andBatchNumLessThanOrEqualTo(Integer value) {
			addCriterion("batch_num <=", value, "batchNum");
			return (Criteria) this;
		}

		public Criteria andBatchNumIn(List<Integer> values) {
			addCriterion("batch_num in", values, "batchNum");
			return (Criteria) this;
		}

		public Criteria andBatchNumNotIn(List<Integer> values) {
			addCriterion("batch_num not in", values, "batchNum");
			return (Criteria) this;
		}

		public Criteria andBatchNumBetween(Integer value1, Integer value2) {
			addCriterion("batch_num between", value1, value2, "batchNum");
			return (Criteria) this;
		}

		public Criteria andBatchNumNotBetween(Integer value1, Integer value2) {
			addCriterion("batch_num not between", value1, value2, "batchNum");
			return (Criteria) this;
		}

		public Criteria andSignIsNull() {
			addCriterion("sign is null");
			return (Criteria) this;
		}

		public Criteria andSignIsNotNull() {
			addCriterion("sign is not null");
			return (Criteria) this;
		}

		public Criteria andSignEqualTo(String value) {
			addCriterion("sign =", value, "sign");
			return (Criteria) this;
		}

		public Criteria andSignNotEqualTo(String value) {
			addCriterion("sign <>", value, "sign");
			return (Criteria) this;
		}

		public Criteria andSignGreaterThan(String value) {
			addCriterion("sign >", value, "sign");
			return (Criteria) this;
		}

		public Criteria andSignGreaterThanOrEqualTo(String value) {
			addCriterion("sign >=", value, "sign");
			return (Criteria) this;
		}

		public Criteria andSignLessThan(String value) {
			addCriterion("sign <", value, "sign");
			return (Criteria) this;
		}

		public Criteria andSignLessThanOrEqualTo(String value) {
			addCriterion("sign <=", value, "sign");
			return (Criteria) this;
		}

		public Criteria andSignLike(String value) {
			addCriterion("sign like", value, "sign");
			return (Criteria) this;
		}

		public Criteria andSignNotLike(String value) {
			addCriterion("sign not like", value, "sign");
			return (Criteria) this;
		}

		public Criteria andSignIn(List<String> values) {
			addCriterion("sign in", values, "sign");
			return (Criteria) this;
		}

		public Criteria andSignNotIn(List<String> values) {
			addCriterion("sign not in", values, "sign");
			return (Criteria) this;
		}

		public Criteria andSignBetween(String value1, String value2) {
			addCriterion("sign between", value1, value2, "sign");
			return (Criteria) this;
		}

		public Criteria andSignNotBetween(String value1, String value2) {
			addCriterion("sign not between", value1, value2, "sign");
			return (Criteria) this;
		}

		public Criteria andCompanyChannelIsNull() {
			addCriterion("company_channel is null");
			return (Criteria) this;
		}

		public Criteria andCompanyChannelIsNotNull() {
			addCriterion("company_channel is not null");
			return (Criteria) this;
		}

		public Criteria andCompanyChannelEqualTo(Boolean value) {
			addCriterion("company_channel =", value, "companyChannel");
			return (Criteria) this;
		}

		public Criteria andCompanyChannelNotEqualTo(Boolean value) {
			addCriterion("company_channel <>", value, "companyChannel");
			return (Criteria) this;
		}

		public Criteria andCompanyChannelGreaterThan(Boolean value) {
			addCriterion("company_channel >", value, "companyChannel");
			return (Criteria) this;
		}

		public Criteria andCompanyChannelGreaterThanOrEqualTo(Boolean value) {
			addCriterion("company_channel >=", value, "companyChannel");
			return (Criteria) this;
		}

		public Criteria andCompanyChannelLessThan(Boolean value) {
			addCriterion("company_channel <", value, "companyChannel");
			return (Criteria) this;
		}

		public Criteria andCompanyChannelLessThanOrEqualTo(Boolean value) {
			addCriterion("company_channel <=", value, "companyChannel");
			return (Criteria) this;
		}

		public Criteria andCompanyChannelIn(List<Boolean> values) {
			addCriterion("company_channel in", values, "companyChannel");
			return (Criteria) this;
		}

		public Criteria andCompanyChannelNotIn(List<Boolean> values) {
			addCriterion("company_channel not in", values, "companyChannel");
			return (Criteria) this;
		}

		public Criteria andCompanyChannelBetween(Boolean value1, Boolean value2) {
			addCriterion("company_channel between", value1, value2, "companyChannel");
			return (Criteria) this;
		}

		public Criteria andCompanyChannelNotBetween(Boolean value1, Boolean value2) {
			addCriterion("company_channel not between", value1, value2, "companyChannel");
			return (Criteria) this;
		}

		public Criteria andInternationalIsNull() {
			addCriterion("international is null");
			return (Criteria) this;
		}

		public Criteria andInternationalIsNotNull() {
			addCriterion("international is not null");
			return (Criteria) this;
		}

		public Criteria andInternationalEqualTo(Boolean value) {
			addCriterion("international =", value, "international");
			return (Criteria) this;
		}

		public Criteria andInternationalNotEqualTo(Boolean value) {
			addCriterion("international <>", value, "international");
			return (Criteria) this;
		}

		public Criteria andInternationalGreaterThan(Boolean value) {
			addCriterion("international >", value, "international");
			return (Criteria) this;
		}

		public Criteria andInternationalGreaterThanOrEqualTo(Boolean value) {
			addCriterion("international >=", value, "international");
			return (Criteria) this;
		}

		public Criteria andInternationalLessThan(Boolean value) {
			addCriterion("international <", value, "international");
			return (Criteria) this;
		}

		public Criteria andInternationalLessThanOrEqualTo(Boolean value) {
			addCriterion("international <=", value, "international");
			return (Criteria) this;
		}

		public Criteria andInternationalIn(List<Boolean> values) {
			addCriterion("international in", values, "international");
			return (Criteria) this;
		}

		public Criteria andInternationalNotIn(List<Boolean> values) {
			addCriterion("international not in", values, "international");
			return (Criteria) this;
		}

		public Criteria andInternationalBetween(Boolean value1, Boolean value2) {
			addCriterion("international between", value1, value2, "international");
			return (Criteria) this;
		}

		public Criteria andInternationalNotBetween(Boolean value1, Boolean value2) {
			addCriterion("international not between", value1, value2, "international");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("remark is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("remark is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("remark =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("remark <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("remark >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("remark >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("remark <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("remark <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("remark like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("remark not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("remark in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("remark not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("remark between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("remark not between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdIsNull() {
			addCriterion("create_user_id is null");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdIsNotNull() {
			addCriterion("create_user_id is not null");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdEqualTo(Long value) {
			addCriterion("create_user_id =", value, "createUserId");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdNotEqualTo(Long value) {
			addCriterion("create_user_id <>", value, "createUserId");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdGreaterThan(Long value) {
			addCriterion("create_user_id >", value, "createUserId");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdGreaterThanOrEqualTo(Long value) {
			addCriterion("create_user_id >=", value, "createUserId");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdLessThan(Long value) {
			addCriterion("create_user_id <", value, "createUserId");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdLessThanOrEqualTo(Long value) {
			addCriterion("create_user_id <=", value, "createUserId");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdIn(List<Long> values) {
			addCriterion("create_user_id in", values, "createUserId");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdNotIn(List<Long> values) {
			addCriterion("create_user_id not in", values, "createUserId");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdBetween(Long value1, Long value2) {
			addCriterion("create_user_id between", value1, value2, "createUserId");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdNotBetween(Long value1, Long value2) {
			addCriterion("create_user_id not between", value1, value2, "createUserId");
			return (Criteria) this;
		}

		public Criteria andCreateUserNameIsNull() {
			addCriterion("create_user_name is null");
			return (Criteria) this;
		}

		public Criteria andCreateUserNameIsNotNull() {
			addCriterion("create_user_name is not null");
			return (Criteria) this;
		}

		public Criteria andCreateUserNameEqualTo(String value) {
			addCriterion("create_user_name =", value, "createUserName");
			return (Criteria) this;
		}

		public Criteria andCreateUserNameNotEqualTo(String value) {
			addCriterion("create_user_name <>", value, "createUserName");
			return (Criteria) this;
		}

		public Criteria andCreateUserNameGreaterThan(String value) {
			addCriterion("create_user_name >", value, "createUserName");
			return (Criteria) this;
		}

		public Criteria andCreateUserNameGreaterThanOrEqualTo(String value) {
			addCriterion("create_user_name >=", value, "createUserName");
			return (Criteria) this;
		}

		public Criteria andCreateUserNameLessThan(String value) {
			addCriterion("create_user_name <", value, "createUserName");
			return (Criteria) this;
		}

		public Criteria andCreateUserNameLessThanOrEqualTo(String value) {
			addCriterion("create_user_name <=", value, "createUserName");
			return (Criteria) this;
		}

		public Criteria andCreateUserNameLike(String value) {
			addCriterion("create_user_name like", value, "createUserName");
			return (Criteria) this;
		}

		public Criteria andCreateUserNameNotLike(String value) {
			addCriterion("create_user_name not like", value, "createUserName");
			return (Criteria) this;
		}

		public Criteria andCreateUserNameIn(List<String> values) {
			addCriterion("create_user_name in", values, "createUserName");
			return (Criteria) this;
		}

		public Criteria andCreateUserNameNotIn(List<String> values) {
			addCriterion("create_user_name not in", values, "createUserName");
			return (Criteria) this;
		}

		public Criteria andCreateUserNameBetween(String value1, String value2) {
			addCriterion("create_user_name between", value1, value2, "createUserName");
			return (Criteria) this;
		}

		public Criteria andCreateUserNameNotBetween(String value1, String value2) {
			addCriterion("create_user_name not between", value1, value2, "createUserName");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNull() {
			addCriterion("create_date is null");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNotNull() {
			addCriterion("create_date is not null");
			return (Criteria) this;
		}

		public Criteria andCreateDateEqualTo(Date value) {
			addCriterion("create_date =", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotEqualTo(Date value) {
			addCriterion("create_date <>", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThan(Date value) {
			addCriterion("create_date >", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("create_date >=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThan(Date value) {
			addCriterion("create_date <", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThanOrEqualTo(Date value) {
			addCriterion("create_date <=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateIn(List<Date> values) {
			addCriterion("create_date in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotIn(List<Date> values) {
			addCriterion("create_date not in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateBetween(Date value1, Date value2) {
			addCriterion("create_date between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotBetween(Date value1, Date value2) {
			addCriterion("create_date not between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andModifiedUserIdIsNull() {
			addCriterion("modified_user_id is null");
			return (Criteria) this;
		}

		public Criteria andModifiedUserIdIsNotNull() {
			addCriterion("modified_user_id is not null");
			return (Criteria) this;
		}

		public Criteria andModifiedUserIdEqualTo(Long value) {
			addCriterion("modified_user_id =", value, "modifiedUserId");
			return (Criteria) this;
		}

		public Criteria andModifiedUserIdNotEqualTo(Long value) {
			addCriterion("modified_user_id <>", value, "modifiedUserId");
			return (Criteria) this;
		}

		public Criteria andModifiedUserIdGreaterThan(Long value) {
			addCriterion("modified_user_id >", value, "modifiedUserId");
			return (Criteria) this;
		}

		public Criteria andModifiedUserIdGreaterThanOrEqualTo(Long value) {
			addCriterion("modified_user_id >=", value, "modifiedUserId");
			return (Criteria) this;
		}

		public Criteria andModifiedUserIdLessThan(Long value) {
			addCriterion("modified_user_id <", value, "modifiedUserId");
			return (Criteria) this;
		}

		public Criteria andModifiedUserIdLessThanOrEqualTo(Long value) {
			addCriterion("modified_user_id <=", value, "modifiedUserId");
			return (Criteria) this;
		}

		public Criteria andModifiedUserIdIn(List<Long> values) {
			addCriterion("modified_user_id in", values, "modifiedUserId");
			return (Criteria) this;
		}

		public Criteria andModifiedUserIdNotIn(List<Long> values) {
			addCriterion("modified_user_id not in", values, "modifiedUserId");
			return (Criteria) this;
		}

		public Criteria andModifiedUserIdBetween(Long value1, Long value2) {
			addCriterion("modified_user_id between", value1, value2, "modifiedUserId");
			return (Criteria) this;
		}

		public Criteria andModifiedUserIdNotBetween(Long value1, Long value2) {
			addCriterion("modified_user_id not between", value1, value2, "modifiedUserId");
			return (Criteria) this;
		}

		public Criteria andModifiedUserNameIsNull() {
			addCriterion("modified_user_name is null");
			return (Criteria) this;
		}

		public Criteria andModifiedUserNameIsNotNull() {
			addCriterion("modified_user_name is not null");
			return (Criteria) this;
		}

		public Criteria andModifiedUserNameEqualTo(String value) {
			addCriterion("modified_user_name =", value, "modifiedUserName");
			return (Criteria) this;
		}

		public Criteria andModifiedUserNameNotEqualTo(String value) {
			addCriterion("modified_user_name <>", value, "modifiedUserName");
			return (Criteria) this;
		}

		public Criteria andModifiedUserNameGreaterThan(String value) {
			addCriterion("modified_user_name >", value, "modifiedUserName");
			return (Criteria) this;
		}

		public Criteria andModifiedUserNameGreaterThanOrEqualTo(String value) {
			addCriterion("modified_user_name >=", value, "modifiedUserName");
			return (Criteria) this;
		}

		public Criteria andModifiedUserNameLessThan(String value) {
			addCriterion("modified_user_name <", value, "modifiedUserName");
			return (Criteria) this;
		}

		public Criteria andModifiedUserNameLessThanOrEqualTo(String value) {
			addCriterion("modified_user_name <=", value, "modifiedUserName");
			return (Criteria) this;
		}

		public Criteria andModifiedUserNameLike(String value) {
			addCriterion("modified_user_name like", value, "modifiedUserName");
			return (Criteria) this;
		}

		public Criteria andModifiedUserNameNotLike(String value) {
			addCriterion("modified_user_name not like", value, "modifiedUserName");
			return (Criteria) this;
		}

		public Criteria andModifiedUserNameIn(List<String> values) {
			addCriterion("modified_user_name in", values, "modifiedUserName");
			return (Criteria) this;
		}

		public Criteria andModifiedUserNameNotIn(List<String> values) {
			addCriterion("modified_user_name not in", values, "modifiedUserName");
			return (Criteria) this;
		}

		public Criteria andModifiedUserNameBetween(String value1, String value2) {
			addCriterion("modified_user_name between", value1, value2, "modifiedUserName");
			return (Criteria) this;
		}

		public Criteria andModifiedUserNameNotBetween(String value1, String value2) {
			addCriterion("modified_user_name not between", value1, value2, "modifiedUserName");
			return (Criteria) this;
		}

		public Criteria andModifiedDateIsNull() {
			addCriterion("modified_date is null");
			return (Criteria) this;
		}

		public Criteria andModifiedDateIsNotNull() {
			addCriterion("modified_date is not null");
			return (Criteria) this;
		}

		public Criteria andModifiedDateEqualTo(Date value) {
			addCriterion("modified_date =", value, "modifiedDate");
			return (Criteria) this;
		}

		public Criteria andModifiedDateNotEqualTo(Date value) {
			addCriterion("modified_date <>", value, "modifiedDate");
			return (Criteria) this;
		}

		public Criteria andModifiedDateGreaterThan(Date value) {
			addCriterion("modified_date >", value, "modifiedDate");
			return (Criteria) this;
		}

		public Criteria andModifiedDateGreaterThanOrEqualTo(Date value) {
			addCriterion("modified_date >=", value, "modifiedDate");
			return (Criteria) this;
		}

		public Criteria andModifiedDateLessThan(Date value) {
			addCriterion("modified_date <", value, "modifiedDate");
			return (Criteria) this;
		}

		public Criteria andModifiedDateLessThanOrEqualTo(Date value) {
			addCriterion("modified_date <=", value, "modifiedDate");
			return (Criteria) this;
		}

		public Criteria andModifiedDateIn(List<Date> values) {
			addCriterion("modified_date in", values, "modifiedDate");
			return (Criteria) this;
		}

		public Criteria andModifiedDateNotIn(List<Date> values) {
			addCriterion("modified_date not in", values, "modifiedDate");
			return (Criteria) this;
		}

		public Criteria andModifiedDateBetween(Date value1, Date value2) {
			addCriterion("modified_date between", value1, value2, "modifiedDate");
			return (Criteria) this;
		}

		public Criteria andModifiedDateNotBetween(Date value1, Date value2) {
			addCriterion("modified_date not between", value1, value2, "modifiedDate");
			return (Criteria) this;
		}

		public Criteria andValidIsNull() {
			addCriterion("valid is null");
			return (Criteria) this;
		}

		public Criteria andValidIsNotNull() {
			addCriterion("valid is not null");
			return (Criteria) this;
		}

		public Criteria andValidEqualTo(Boolean value) {
			addCriterion("valid =", value, "valid");
			return (Criteria) this;
		}

		public Criteria andValidNotEqualTo(Boolean value) {
			addCriterion("valid <>", value, "valid");
			return (Criteria) this;
		}

		public Criteria andValidGreaterThan(Boolean value) {
			addCriterion("valid >", value, "valid");
			return (Criteria) this;
		}

		public Criteria andValidGreaterThanOrEqualTo(Boolean value) {
			addCriterion("valid >=", value, "valid");
			return (Criteria) this;
		}

		public Criteria andValidLessThan(Boolean value) {
			addCriterion("valid <", value, "valid");
			return (Criteria) this;
		}

		public Criteria andValidLessThanOrEqualTo(Boolean value) {
			addCriterion("valid <=", value, "valid");
			return (Criteria) this;
		}

		public Criteria andValidIn(List<Boolean> values) {
			addCriterion("valid in", values, "valid");
			return (Criteria) this;
		}

		public Criteria andValidNotIn(List<Boolean> values) {
			addCriterion("valid not in", values, "valid");
			return (Criteria) this;
		}

		public Criteria andValidBetween(Boolean value1, Boolean value2) {
			addCriterion("valid between", value1, value2, "valid");
			return (Criteria) this;
		}

		public Criteria andValidNotBetween(Boolean value1, Boolean value2) {
			addCriterion("valid not between", value1, value2, "valid");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_sys_sms_config
	 * @mbg.generated  Mon Aug 20 20:07:00 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**9
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sys_sms_config
     *
     * @mbg.generated do_not_delete_during_merge 2018-07-10 15:11:04
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }
}