server:
  port: 2007
  servlet:
      context-path: /mktcenter
spring:
  redis:
      database: 7
  profiles:
    active: basecontroller,commonutilslocal
  swagger:
    show: true
  application:
    name: mktcenter
#  security:
#    enabled: false
#    user:
#      name: root
#      password: root
  datasource:
    url: jdbc:mysql://bizvane-2018.mysql.polardb.rds.aliyuncs.com:3306/bizvane-mktcenter?useUnicode=true&characterEncoding=utf-8
    username: bizvane_2018
    password: SF_bizvane20180613
    driver-class-name: com.mysql.jdbc.Driver
  data:
    mongodb:
      database: "1"
eureka:
  instance:
    metadata-map:
#      user.name: ${spring.security.user.name}
#      user.password: ${spring.security.user.password}
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      defaultZone: http://47.97.50.134:8761/eureka/
#management:
#  endpoints:
#    web.exposure.include: "*"
#  endpoint:
#    health:
#      show-details: ALWAYS
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mybatis/*Mapper.xml
logging:
  config: classpath:logback.xml
#  level:
#    com.bizvane.mktcenterserviceimpl.mappers: debug
#    com.bizvane.mktcenterserviceimpl: debug

# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql




xxl:
  job:
    admin:
      ### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
      addresses: http://192.168.102.201:8099
    ### xxl-job executor address
    executor:
      appname: mktcenter
      ip:
      port: 9007
      ### xxl-job log path
      logpath: /data/applogs/xxl-job/jobhandler
      ### xxl-job log retention days
      logretentiondays: -1
    ### xxl-job, access token
    accessToken:
