server:
  port: 2007
  servlet:
    context-path: /mktcenter.api
spring:
  redis:
    database: 7
    host:  r-bp18995999cbc2f4.redis.rds.aliyuncs.com
    port: 6379
    password: BIZvane2019
    jedis:
      pool:
        max-active: 100
        max-idle: 8
        max-wait: 2000ms
        min-idle: 0
  swagger:
    show: true
  application:
    name: mktcenter-prod
  datasource:
    url: jdbc:mysql://pc-bp1o4oa69njltr9er-rw-vpc.rwlb.rds.aliyuncs.com:3306/crm?useUnicode=true&characterEncoding=utf-8
    username: application
    password: SF#2018bizvane
    driver-class-name: com.mysql.jdbc.Driver
  data:
    mongodb:
      uri: "mongodb://dds-bp14278823e03ba41.mongodb.rds.aliyuncs.com:3717/?AutoConnectRetry=true"
      database: "crm"
      username: crm
      password: BIZvane2019
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
eureka:
  instance:
    metadata-map:
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      defaultZone: http://172.16.147.203:8761/eureka/,http://172.16.147.198:8761/eureka/
management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mybatis/*Mapper.xml
logging:
  config: classpath:logback-local.xml
  level:
    root: info
    com.bizvane.mktcenterserviceimpl.mappers: debug

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

xxl:
  job:
    admin:
      ### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
      addresses: http://172.16.147.191:8080/job/
    ### xxl-job executor address
    executor:
      appname: ${spring.application.name}
      ip:
      port: 9007
      ### xxl-job log path
      logpath: log/job
      ### xxl-job log retention days
      logretentiondays: -1
    ### xxl-job, access token
    accessToken:

feign:
  client:
    centerstage:
      name: centerstage-prod
      path: centerstage.api
    coupon:
      name: coupon-prod
      path: coupon.api
    members:
      name: members-prod
      path: members.api
    message:
      name: message-prod
      path: message.api
    wechat:
      name: wechat-prod
      path: wechat
    applet:
      name: applet-prod
      path: applet.api
    centercontrol:
      name: centercontrol-prod
      path: centercontrol.api
    fitment:
      name: fitment-prod
      path: fitment.api

rocketmq:
  onsaddr: http://onsaddr-internal.aliyun.com:8080/rocketmq/nsaddr4client-internal
  accessKey: LTAIpoqUHsXq6q7r
  secretKey: 0ZJ7bfxXJLT8TpOKvZU3i4YWuhvJzs
  addr:
  environment: prod

threadPool:
  corePoolSize: 16
  maximumPoolSize: 48
  keepAliveTime: 60
  queueCapacity: 99999

qiniu:
  accessKey: Jv79lFtLNDBj1XJ6vkXkemnRN5LIOSXMeDOvW35n
  secretKey: HIKXNXr12qRhpIAsdI8xTaX87LeTqqLGjXB_RgDf
  bucketNm: bizvane-prod
  domain: static.bizvane.com

activity:
  qrcodeurl: /qrcode?activityCode=
bitdata:
  businessNum: c10153
  apiKey: e898e91ff9758a3b01b84c920158d1a8
  url: http://open.bizvane.com:8888/api/open-data-analysis/

tenant:
  isEnabledTenantInterceptor: false
ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000