server:
  port: 2007
  servlet:
    context-path: /mktcenter.api
spring:
  redis:
    database: 7
    host: 192.168.1.50
    port: 6379
    password: bizvane
    jedis:
      pool:
        max-active: 100
        max-idle: 8
        max-wait: 2000ms
        min-idle: 0
  swagger:
    show: true
  application:
    name: mktcenter-test
  #  security:
  #    enabled: false
  #    user:
  #      name: root
  #      password: root
  datasource:
    url: jdbc:mysql://bizvane-2018.mysql.polardb.rds.aliyuncs.com:3306/bizvane3?useUnicode=true&characterEncoding=utf-8
    username: bizvane_2018
    password: SF_bizvane20180613
    driver-class-name: com.mysql.jdbc.Driver
  data:
    mongodb:
      database: "7"
      uri: "mongodb://192.168.1.51:27017/?AutoConnectRetry=true"
  elasticsearch:
    cluster-name: my-esLearn
    cluster-nodes: 192.168.1.45:9300
    repositories:
      enabled: true
  kafka:
    producer:
      bootstrap-servers: "192.168.1.50:9092"
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      batch-size: 16384
      buffer-memory: 33554432
      retries: 0
      acks: "1"
    consumer:
      bootstrap-servers: "192.168.1.50:9092"
      enable-auto-commit: false
      auto-offset-reset: "earliest"
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      session-timeout: 30000
      request-timeout: 40000
      heartbeat-interval: 29000ms
      max-partition-fetch-bytes: 524288
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  zipkin:
    baseUrl: http://192.168.2.15:9411
    sleuth:
      sampler:
        probability: 1.0
      scheduled:
        enabled: false
eureka:
  instance:
    metadata-map:
      #      user.name: ${spring.security.user.name}
      #      user.password: ${spring.security.user.password}
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      defaultZone: http://192.168.1.46:8761/eureka/
management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mybatis/*Mapper.xml
logging:
  config: classpath:logback-local.xml
  level:
    root: info
    com.bizvane.mktcenterserviceimpl.mappers: debug

# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

xxl:
  job:
    admin:
      ### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
      addresses: http://192.168.1.49:8080
    ### xxl-job executor address
    executor:
      appname: ${spring.application.name}
      ip:
      port: 9007
      ### xxl-job log path
      logpath: log/job
      ### xxl-job log retention days
      logretentiondays: -1
    ### xxl-job, access token
    accessToken:

feign:
  client:
    centerstage:
      name: centerstage-test
      path: centerstage.api
    coupon:
      name: coupon-test
      path: coupon.api
    members:
      name: members-test
      path: members.api
    message:
      name: message-test
      path: message.api
    wechat:
      name: wechat-test
      path: wechat
    applet:
      name: applet-test
      path: applet.api
    centercontrol:
      name: centercontrol-test
      path: centercontrol.api
    fitment:
      name: fitment-test
      path: fitment.api

rocketmq:
  onsaddr:
  accessKey: LTAIpoqUHsXq6q7r
  secretKey: 0ZJ7bfxXJLT8TpOKvZU3i4YWuhvJzs
  addr: 192.168.1.50:9876
  environment: uat
  
  

threadPool:
  corePoolSize: 16
  maximumPoolSize: 48
  keepAliveTime: 60
  queueCapacity: 99999

qiniu:
  accessKey: Jv79lFtLNDBj1XJ6vkXkemnRN5LIOSXMeDOvW35n
  secretKey: HIKXNXr12qRhpIAsdI8xTaX87LeTqqLGjXB_RgDf
  bucketNm: bizvane01
  domain: qi.test.bizvane.cn

activity:
  qrcodeurl: /qrcode?activityCode=

bitdata:
  businessNum: testbz
  apiKey: 4199454b3cac0c02b48fd5a9c67c00c0
  url: http://bizvane.f3322.net:58765/api/open-data-analysis/

tenant:
  isEnabledTenantInterceptor: false
ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000

#审计日志#
rmq:
  ONSAddr: 192.168.1.50:9876
  accessKey: LTAIpoqUHsXq6q7r
  secretKey: 0ZJ7bfxXJLT8TpOKvZU3i4YWuhvJzs